//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSW.Nbt.ChemWatchCommonServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Languages", Namespace="", ItemName="Language")]
    [System.SerializableAttribute()]
    public class Languages : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.Language> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Language", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Language : ChemSW.Nbt.ChemWatchCommonServices.BaseNamedEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageWhenNotObviousField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UILanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CommonLanguageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageIdField, value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageWhenNotObvious {
            get {
                return this.LanguageWhenNotObviousField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageWhenNotObviousField, value) != true)) {
                    this.LanguageWhenNotObviousField = value;
                    this.RaisePropertyChanged("LanguageWhenNotObvious");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool UILanguage {
            get {
                return this.UILanguageField;
            }
            set {
                if ((this.UILanguageField.Equals(value) != true)) {
                    this.UILanguageField = value;
                    this.RaisePropertyChanged("UILanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool CommonLanguage {
            get {
                return this.CommonLanguageField;
            }
            set {
                if ((this.CommonLanguageField.Equals(value) != true)) {
                    this.CommonLanguageField = value;
                    this.RaisePropertyChanged("CommonLanguage");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOflong", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.TranslationCodeText))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.BaseCodeEntityOflong))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.HazardCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.RiskCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.SafetyCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.Code))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.CodePhrase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.BaseNamedEntityOflong))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.DocumentType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.DocumentSource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.Language))]
    public partial class BaseEntityOflong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationCodeText", Namespace="http://schemas.datacontract.org/2004/07/Chemwatch.Entities.TranslationCodes")]
    [System.SerializableAttribute()]
    public partial class TranslationCodeText : ChemSW.Nbt.ChemWatchCommonServices.BaseEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastEditedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TranslationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TranslationCodeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastEdited {
            get {
                return this.LastEditedField;
            }
            set {
                if ((this.LastEditedField.Equals(value) != true)) {
                    this.LastEditedField = value;
                    this.RaisePropertyChanged("LastEdited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Short {
            get {
                return this.ShortField;
            }
            set {
                if ((this.ShortField.Equals(value) != true)) {
                    this.ShortField = value;
                    this.RaisePropertyChanged("Short");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TranslationCode {
            get {
                return this.TranslationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TranslationCodeField, value) != true)) {
                    this.TranslationCodeField = value;
                    this.RaisePropertyChanged("TranslationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TranslationCodeId {
            get {
                return this.TranslationCodeIdField;
            }
            set {
                if ((this.TranslationCodeIdField.Equals(value) != true)) {
                    this.TranslationCodeIdField = value;
                    this.RaisePropertyChanged("TranslationCodeId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseCodeEntityOflong", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.HazardCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.RiskCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.SafetyCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.Code))]
    public partial class BaseCodeEntityOflong : ChemSW.Nbt.ChemWatchCommonServices.BaseEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HazardCode", Namespace="")]
    [System.SerializableAttribute()]
    public partial class HazardCode : ChemSW.Nbt.ChemWatchCommonServices.BaseCodeEntityOflong {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrecautionaryCode", Namespace="")]
    [System.SerializableAttribute()]
    public partial class PrecautionaryCode : ChemSW.Nbt.ChemWatchCommonServices.BaseCodeEntityOflong {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RiskCode", Namespace="")]
    [System.SerializableAttribute()]
    public partial class RiskCode : ChemSW.Nbt.ChemWatchCommonServices.BaseCodeEntityOflong {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SafetyCode", Namespace="")]
    [System.SerializableAttribute()]
    public partial class SafetyCode : ChemSW.Nbt.ChemWatchCommonServices.BaseCodeEntityOflong {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Code", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Code : ChemSW.Nbt.ChemWatchCommonServices.BaseCodeEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.CodePhrase CodePhraseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.CodePhrase CodePhrase {
            get {
                return this.CodePhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePhraseField, value) != true)) {
                    this.CodePhraseField = value;
                    this.RaisePropertyChanged("CodePhrase");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodePhrase", Namespace="")]
    [System.SerializableAttribute()]
    public partial class CodePhrase : ChemSW.Nbt.ChemWatchCommonServices.BaseEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhraseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodeId {
            get {
                return this.CodeIdField;
            }
            set {
                if ((this.CodeIdField.Equals(value) != true)) {
                    this.CodeIdField = value;
                    this.RaisePropertyChanged("CodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phrase {
            get {
                return this.PhraseField;
            }
            set {
                if ((object.ReferenceEquals(this.PhraseField, value) != true)) {
                    this.PhraseField = value;
                    this.RaisePropertyChanged("Phrase");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseNamedEntityOflong", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.Country))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.DocumentType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.DocumentSource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.Language))]
    public partial class BaseNamedEntityOflong : ChemSW.Nbt.ChemWatchCommonServices.BaseEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Country : ChemSW.Nbt.ChemWatchCommonServices.BaseNamedEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentType", Namespace="")]
    [System.SerializableAttribute()]
    public partial class DocumentType : ChemSW.Nbt.ChemWatchCommonServices.BaseNamedEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentSource", Namespace="")]
    [System.SerializableAttribute()]
    public partial class DocumentSource : ChemSW.Nbt.ChemWatchCommonServices.BaseNamedEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Countries", Namespace="", ItemName="Country")]
    [System.SerializableAttribute()]
    public class Countries : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.Country> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DocumentTypes", Namespace="", ItemName="DocumentType")]
    [System.SerializableAttribute()]
    public class DocumentTypes : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.DocumentType> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DocumentSources", Namespace="", ItemName="DocumentSource")]
    [System.SerializableAttribute()]
    public class DocumentSources : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.DocumentSource> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="HazardCodes", Namespace="", ItemName="HazardCode")]
    [System.SerializableAttribute()]
    public class HazardCodes : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.HazardCode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name=" PrecautionaryCodes", Namespace="", ItemName="PrecautionaryCode")]
    [System.SerializableAttribute()]
    public class PrecautionaryCodes : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RiskCodes", Namespace="", ItemName="RiskCode")]
    [System.SerializableAttribute()]
    public class RiskCodes : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.RiskCode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SafetyCodes", Namespace="", ItemName="SafetyCode")]
    [System.SerializableAttribute()]
    public class SafetyCodes : System.Collections.Generic.List<ChemSW.Nbt.ChemWatchCommonServices.SafetyCode> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GHSConditions", Namespace="")]
    [System.SerializableAttribute()]
    public partial class GHSConditions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> BoilingPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CWNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DGCValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> FreezePointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HazardCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] IngredientCWNumbersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LowerExplosiveLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackingGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhysicalStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.RiskCodes RiskCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> UpperExplosiveLimitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> BoilingPoint {
            get {
                return this.BoilingPointField;
            }
            set {
                if ((this.BoilingPointField.Equals(value) != true)) {
                    this.BoilingPointField = value;
                    this.RaisePropertyChanged("BoilingPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CWNumber {
            get {
                return this.CWNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CWNumberField, value) != true)) {
                    this.CWNumberField = value;
                    this.RaisePropertyChanged("CWNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DGCValues {
            get {
                return this.DGCValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.DGCValuesField, value) != true)) {
                    this.DGCValuesField = value;
                    this.RaisePropertyChanged("DGCValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FreezePoint {
            get {
                return this.FreezePointField;
            }
            set {
                if ((this.FreezePointField.Equals(value) != true)) {
                    this.FreezePointField = value;
                    this.RaisePropertyChanged("FreezePoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] HazardCodes {
            get {
                return this.HazardCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.HazardCodesField, value) != true)) {
                    this.HazardCodesField = value;
                    this.RaisePropertyChanged("HazardCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] IngredientCWNumbers {
            get {
                return this.IngredientCWNumbersField;
            }
            set {
                if ((object.ReferenceEquals(this.IngredientCWNumbersField, value) != true)) {
                    this.IngredientCWNumbersField = value;
                    this.RaisePropertyChanged("IngredientCWNumbers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LowerExplosiveLimit {
            get {
                return this.LowerExplosiveLimitField;
            }
            set {
                if ((this.LowerExplosiveLimitField.Equals(value) != true)) {
                    this.LowerExplosiveLimitField = value;
                    this.RaisePropertyChanged("LowerExplosiveLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackingGroup {
            get {
                return this.PackingGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.PackingGroupField, value) != true)) {
                    this.PackingGroupField = value;
                    this.RaisePropertyChanged("PackingGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhysicalState {
            get {
                return this.PhysicalStateField;
            }
            set {
                if ((object.ReferenceEquals(this.PhysicalStateField, value) != true)) {
                    this.PhysicalStateField = value;
                    this.RaisePropertyChanged("PhysicalState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.RiskCodes RiskCodes {
            get {
                return this.RiskCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.RiskCodesField, value) != true)) {
                    this.RiskCodesField = value;
                    this.RaisePropertyChanged("RiskCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueNumber {
            get {
                return this.UniqueNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueNumberField, value) != true)) {
                    this.UniqueNumberField = value;
                    this.RaisePropertyChanged("UniqueNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> UpperExplosiveLimit {
            get {
                return this.UpperExplosiveLimitField;
            }
            set {
                if ((this.UpperExplosiveLimitField.Equals(value) != true)) {
                    this.UpperExplosiveLimitField = value;
                    this.RaisePropertyChanged("UpperExplosiveLimit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GHSClassification", Namespace="")]
    [System.SerializableAttribute()]
    public partial class GHSClassification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CLPClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes DisplayCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] GHSPicturesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.HazardCodes HazardCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.HazardCodes HazardCodesWithoutCountrySpecificField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes PreventationCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes ResponseCodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SignalWordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes StorageCodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CLPClassification {
            get {
                return this.CLPClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.CLPClassificationField, value) != true)) {
                    this.CLPClassificationField = value;
                    this.RaisePropertyChanged("CLPClassification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes DisplayCodes {
            get {
                return this.DisplayCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayCodesField, value) != true)) {
                    this.DisplayCodesField = value;
                    this.RaisePropertyChanged("DisplayCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] GHSPictures {
            get {
                return this.GHSPicturesField;
            }
            set {
                if ((object.ReferenceEquals(this.GHSPicturesField, value) != true)) {
                    this.GHSPicturesField = value;
                    this.RaisePropertyChanged("GHSPictures");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.HazardCodes HazardCodes {
            get {
                return this.HazardCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.HazardCodesField, value) != true)) {
                    this.HazardCodesField = value;
                    this.RaisePropertyChanged("HazardCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.HazardCodes HazardCodesWithoutCountrySpecific {
            get {
                return this.HazardCodesWithoutCountrySpecificField;
            }
            set {
                if ((object.ReferenceEquals(this.HazardCodesWithoutCountrySpecificField, value) != true)) {
                    this.HazardCodesWithoutCountrySpecificField = value;
                    this.RaisePropertyChanged("HazardCodesWithoutCountrySpecific");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes PreventationCodes {
            get {
                return this.PreventationCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.PreventationCodesField, value) != true)) {
                    this.PreventationCodesField = value;
                    this.RaisePropertyChanged("PreventationCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes ResponseCodes {
            get {
                return this.ResponseCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodesField, value) != true)) {
                    this.ResponseCodesField = value;
                    this.RaisePropertyChanged("ResponseCodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SignalWords {
            get {
                return this.SignalWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.SignalWordsField, value) != true)) {
                    this.SignalWordsField = value;
                    this.RaisePropertyChanged("SignalWords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes StorageCodes {
            get {
                return this.StorageCodesField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageCodesField, value) != true)) {
                    this.StorageCodesField = value;
                    this.RaisePropertyChanged("StorageCodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfConvertRequest", Namespace="")]
    [System.SerializableAttribute()]
    public partial class PdfConvertRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Html {
            get {
                return this.HtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.HtmlField, value) != true)) {
                    this.HtmlField = value;
                    this.RaisePropertyChanged("Html");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeCollection", Namespace="")]
    [System.SerializableAttribute()]
    public partial class CodeCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.CodeType CodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.Code[] CodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LanguageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.CodeType CodeType {
            get {
                return this.CodeTypeField;
            }
            set {
                if ((this.CodeTypeField.Equals(value) != true)) {
                    this.CodeTypeField = value;
                    this.RaisePropertyChanged("CodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.Code[] Codes {
            get {
                return this.CodesField;
            }
            set {
                if ((object.ReferenceEquals(this.CodesField, value) != true)) {
                    this.CodesField = value;
                    this.RaisePropertyChanged("Codes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CodeType", Namespace="")]
    public enum CodeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Risk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hazard = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRequest", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.GeneralSearchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.GetVendorGroupRequest))]
    public partial class ListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string SortField {
            get {
                return this.SortFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true)) {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int SortType {
            get {
                return this.SortTypeField;
            }
            set {
                if ((this.SortTypeField.Equals(value) != true)) {
                    this.SortTypeField = value;
                    this.RaisePropertyChanged("SortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralSearchRequest", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchCommonServices.GetVendorGroupRequest))]
    public partial class GeneralSearchRequest : ChemSW.Nbt.ChemWatchCommonServices.ListRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetVendorGroupRequest", Namespace="")]
    [System.SerializableAttribute()]
    public partial class GetVendorGroupRequest : ChemSW.Nbt.ChemWatchCommonServices.GeneralSearchRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorGroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gid {
            get {
                return this.GidField;
            }
            set {
                if ((object.ReferenceEquals(this.GidField, value) != true)) {
                    this.GidField = value;
                    this.RaisePropertyChanged("Gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorGroupName {
            get {
                return this.VendorGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorGroupNameField, value) != true)) {
                    this.VendorGroupNameField = value;
                    this.RaisePropertyChanged("VendorGroupName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListResultOfVendorGroup", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ListResultOfVendorGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.VendorGroup[] RowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExact {
            get {
                return this.IsExactField;
            }
            set {
                if ((this.IsExactField.Equals(value) != true)) {
                    this.IsExactField = value;
                    this.RaisePropertyChanged("IsExact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount {
            get {
                return this.RowCountField;
            }
            set {
                if ((this.RowCountField.Equals(value) != true)) {
                    this.RowCountField = value;
                    this.RaisePropertyChanged("RowCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.VendorGroup[] Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((object.ReferenceEquals(this.RowsField, value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VendorGroup", Namespace="")]
    [System.SerializableAttribute()]
    public partial class VendorGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorGroupNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gid {
            get {
                return this.GidField;
            }
            set {
                if ((object.ReferenceEquals(this.GidField, value) != true)) {
                    this.GidField = value;
                    this.RaisePropertyChanged("Gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorGroupId {
            get {
                return this.VendorGroupIdField;
            }
            set {
                if ((this.VendorGroupIdField.Equals(value) != true)) {
                    this.VendorGroupIdField = value;
                    this.RaisePropertyChanged("VendorGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorGroupName {
            get {
                return this.VendorGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorGroupNameField, value) != true)) {
                    this.VendorGroupNameField = value;
                    this.RaisePropertyChanged("VendorGroupName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTranslationTextsRequest", Namespace="")]
    [System.SerializableAttribute()]
    public partial class GetTranslationTextsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationTextGroups", Namespace="")]
    [System.SerializableAttribute()]
    public partial class TranslationTextGroups : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.TranslationTextGroup TextGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchCommonServices.TranslationCodeText[] TextsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.TranslationTextGroup TextGroup {
            get {
                return this.TextGroupField;
            }
            set {
                if ((this.TextGroupField.Equals(value) != true)) {
                    this.TextGroupField = value;
                    this.RaisePropertyChanged("TextGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchCommonServices.TranslationCodeText[] Texts {
            get {
                return this.TextsField;
            }
            set {
                if ((object.ReferenceEquals(this.TextsField, value) != true)) {
                    this.TextsField = value;
                    this.RaisePropertyChanged("Texts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslationTextGroup", Namespace="")]
    public enum TranslationTextGroup : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhysicalState = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WaterSolubility = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhysicalStateDividedSolid = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ChemWatchCommonServices.ICommonService")]
    public interface ICommonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetVersion", ReplyAction="urn:ICommonService/GetVersionResponse")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetLanguages", ReplyAction="urn:ICommonService/GetLanguagesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.Languages GetLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetReportGeneratorLanguages", ReplyAction="urn:ICommonService/GetReportGeneratorLanguagesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.Languages GetReportGeneratorLanguages();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetCountries", ReplyAction="urn:ICommonService/GetCountriesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.Countries GetCountries();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetDocumentTypes", ReplyAction="urn:ICommonService/GetDocumentTypesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.DocumentTypes GetDocumentTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetDocumentSources", ReplyAction="urn:ICommonService/GetDocumentSourcesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.DocumentSources GetDocumentSources();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetHazardCodes", ReplyAction="urn:ICommonService/GetHazardCodesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.HazardCodes GetHazardCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetPrecautionaryCodes", ReplyAction="urn:ICommonService/GetPrecautionaryCodesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes GetPrecautionaryCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetRiskCodes", ReplyAction="urn:ICommonService/GetRiskCodesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.RiskCodes GetRiskCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetSafetyCodes", ReplyAction="urn:ICommonService/GetSafetyCodesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.SafetyCodes GetSafetyCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GenerateGHSClassification", ReplyAction="urn:ICommonService/GenerateGHSClassificationResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.GHSClassification GenerateGHSClassification(ChemSW.Nbt.ChemWatchCommonServices.GHSConditions ghsConditions, string countryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/ConvertToPdf", ReplyAction="urn:ICommonService/ConvertToPdfResponse")]
        System.IO.Stream ConvertToPdf(ChemSW.Nbt.ChemWatchCommonServices.PdfConvertRequest convertRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetAllCodes", ReplyAction="urn:ICommonService/GetAllCodesResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.CodeCollection[] GetAllCodes(int languageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetUserSettings", ReplyAction="urn:ICommonService/GetUserSettingsResponse")]
        System.Collections.Generic.Dictionary<string, string> GetUserSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/SetUserSettings", ReplyAction="urn:ICommonService/SetUserSettingsResponse")]
        void SetUserSettings(System.Collections.Generic.Dictionary<string, string> settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetVendorGroups", ReplyAction="urn:ICommonService/GetVendorGroupsResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.ListResultOfVendorGroup GetVendorGroups(ChemSW.Nbt.ChemWatchCommonServices.GetVendorGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/SetDomainLogo", ReplyAction="urn:ICommonService/SetDomainLogoResponse")]
        void SetDomainLogo(string domain, byte[] logo);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/SetOutbackSettings", ReplyAction="urn:ICommonService/SetOutbackSettingsResponse")]
        void SetOutbackSettings(string domain, System.Collections.Generic.Dictionary<string, string> settings);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetOutbackSettings", ReplyAction="urn:ICommonService/GetOutbackSettingsResponse")]
        System.Collections.Generic.Dictionary<string, string> GetOutbackSettings(string domainName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ICommonService/GetTranslationTexts", ReplyAction="urn:ICommonService/GetTranslationTextsResponse")]
        ChemSW.Nbt.ChemWatchCommonServices.TranslationTextGroups[] GetTranslationTexts(ChemSW.Nbt.ChemWatchCommonServices.GetTranslationTextsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonServiceChannel : ChemSW.Nbt.ChemWatchCommonServices.ICommonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonServiceClient : System.ServiceModel.ClientBase<ChemSW.Nbt.ChemWatchCommonServices.ICommonService>, ChemSW.Nbt.ChemWatchCommonServices.ICommonService {
        
        public CommonServiceClient() {
        }
        
        public CommonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.Languages GetLanguages() {
            return base.Channel.GetLanguages();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.Languages GetReportGeneratorLanguages() {
            return base.Channel.GetReportGeneratorLanguages();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.Countries GetCountries() {
            return base.Channel.GetCountries();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.DocumentTypes GetDocumentTypes() {
            return base.Channel.GetDocumentTypes();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.DocumentSources GetDocumentSources() {
            return base.Channel.GetDocumentSources();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.HazardCodes GetHazardCodes() {
            return base.Channel.GetHazardCodes();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.PrecautionaryCodes GetPrecautionaryCodes() {
            return base.Channel.GetPrecautionaryCodes();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.RiskCodes GetRiskCodes() {
            return base.Channel.GetRiskCodes();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.SafetyCodes GetSafetyCodes() {
            return base.Channel.GetSafetyCodes();
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.GHSClassification GenerateGHSClassification(ChemSW.Nbt.ChemWatchCommonServices.GHSConditions ghsConditions, string countryId) {
            return base.Channel.GenerateGHSClassification(ghsConditions, countryId);
        }
        
        public System.IO.Stream ConvertToPdf(ChemSW.Nbt.ChemWatchCommonServices.PdfConvertRequest convertRequest) {
            return base.Channel.ConvertToPdf(convertRequest);
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.CodeCollection[] GetAllCodes(int languageId) {
            return base.Channel.GetAllCodes(languageId);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetUserSettings() {
            return base.Channel.GetUserSettings();
        }
        
        public void SetUserSettings(System.Collections.Generic.Dictionary<string, string> settings) {
            base.Channel.SetUserSettings(settings);
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.ListResultOfVendorGroup GetVendorGroups(ChemSW.Nbt.ChemWatchCommonServices.GetVendorGroupRequest request) {
            return base.Channel.GetVendorGroups(request);
        }
        
        public void SetDomainLogo(string domain, byte[] logo) {
            base.Channel.SetDomainLogo(domain, logo);
        }
        
        public void SetOutbackSettings(string domain, System.Collections.Generic.Dictionary<string, string> settings) {
            base.Channel.SetOutbackSettings(domain, settings);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetOutbackSettings(string domainName) {
            return base.Channel.GetOutbackSettings(domainName);
        }
        
        public ChemSW.Nbt.ChemWatchCommonServices.TranslationTextGroups[] GetTranslationTexts(ChemSW.Nbt.ChemWatchCommonServices.GetTranslationTextsRequest request) {
            return base.Channel.GetTranslationTexts(request);
        }
    }
}
