//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSW.Nbt.ChemCatCentral {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswC3Params", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswC3Params : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerLoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImportSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string customernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string useridField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessId {
            get {
                return this.AccessIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessIdField, value) != true)) {
                    this.AccessIdField = value;
                    this.RaisePropertyChanged("AccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLoginName {
            get {
                return this.CustomerLoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLoginNameField, value) != true)) {
                    this.CustomerLoginNameField = value;
                    this.RaisePropertyChanged("CustomerLoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataStatus {
            get {
                return this.DataStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.DataStatusField, value) != true)) {
                    this.DataStatusField = value;
                    this.RaisePropertyChanged("DataStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImportSetId {
            get {
                return this.ImportSetIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportSetIdField, value) != true)) {
                    this.ImportSetIdField = value;
                    this.RaisePropertyChanged("ImportSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginPassword {
            get {
                return this.LoginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginPasswordField, value) != true)) {
                    this.LoginPasswordField = value;
                    this.RaisePropertyChanged("LoginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customername {
            get {
                return this.customernameField;
            }
            set {
                if ((object.ReferenceEquals(this.customernameField, value) != true)) {
                    this.customernameField = value;
                    this.RaisePropertyChanged("customername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userid {
            get {
                return this.useridField;
            }
            set {
                if ((object.ReferenceEquals(this.useridField, value) != true)) {
                    this.useridField = value;
                    this.RaisePropertyChanged("userid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswRetObjSearchResults", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswRetObjSearchResults : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.WebSvc.CswWebSvcSessionAuthenticateData.Authentication.Response AuthenticationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] AvailableDataSourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemCatCentral.CswC3Product[] CswC3SearchResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataSourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.WebSvc.CswWebSvcReturnBase.Logging LoggingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.WebSvc.CswWebSvcReturnBase.Performance PerformanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.WebSvc.CswWebSvcReturnBase.Status StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated {
            get {
                return this.AuthenticatedField;
            }
            set {
                if ((this.AuthenticatedField.Equals(value) != true)) {
                    this.AuthenticatedField = value;
                    this.RaisePropertyChanged("Authenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.WebSvc.CswWebSvcSessionAuthenticateData.Authentication.Response Authentication {
            get {
                return this.AuthenticationField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationField, value) != true)) {
                    this.AuthenticationField = value;
                    this.RaisePropertyChanged("Authentication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] AvailableDataSources {
            get {
                return this.AvailableDataSourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableDataSourcesField, value) != true)) {
                    this.AvailableDataSourcesField = value;
                    this.RaisePropertyChanged("AvailableDataSources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemCatCentral.CswC3Product[] CswC3SearchResults {
            get {
                return this.CswC3SearchResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.CswC3SearchResultsField, value) != true)) {
                    this.CswC3SearchResultsField = value;
                    this.RaisePropertyChanged("CswC3SearchResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataSources {
            get {
                return this.DataSourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataSourcesField, value) != true)) {
                    this.DataSourcesField = value;
                    this.RaisePropertyChanged("DataSources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.WebSvc.CswWebSvcReturnBase.Logging Logging {
            get {
                return this.LoggingField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggingField, value) != true)) {
                    this.LoggingField = value;
                    this.RaisePropertyChanged("Logging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.WebSvc.CswWebSvcReturnBase.Performance Performance {
            get {
                return this.PerformanceField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceField, value) != true)) {
                    this.PerformanceField = value;
                    this.RaisePropertyChanged("Performance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.WebSvc.CswWebSvcReturnBase.Status Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswC3Product", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswC3Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CasNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatalogNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImportSetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MolDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MolImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsdsUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObsoleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemCatCentral.CswC3Product.Size[] ProductSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceRowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemCatCentral.CswC3Product.TemplateSlctdExtData[] TemplateSelectedExtensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TradeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CasNo {
            get {
                return this.CasNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CasNoField, value) != true)) {
                    this.CasNoField = value;
                    this.RaisePropertyChanged("CasNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CatalogNo {
            get {
                return this.CatalogNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CatalogNoField, value) != true)) {
                    this.CatalogNoField = value;
                    this.RaisePropertyChanged("CatalogNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData")]
        public string ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formula {
            get {
                return this.FormulaField;
            }
            set {
                if ((object.ReferenceEquals(this.FormulaField, value) != true)) {
                    this.FormulaField = value;
                    this.RaisePropertyChanged("Formula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImportSetId {
            get {
                return this.ImportSetIdField;
            }
            set {
                if ((this.ImportSetIdField.Equals(value) != true)) {
                    this.ImportSetIdField = value;
                    this.RaisePropertyChanged("ImportSetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MolData {
            get {
                return this.MolDataField;
            }
            set {
                if ((object.ReferenceEquals(this.MolDataField, value) != true)) {
                    this.MolDataField = value;
                    this.RaisePropertyChanged("MolData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MolImage {
            get {
                return this.MolImageField;
            }
            set {
                if ((object.ReferenceEquals(this.MolImageField, value) != true)) {
                    this.MolImageField = value;
                    this.RaisePropertyChanged("MolImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsdsUrl {
            get {
                return this.MsdsUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MsdsUrlField, value) != true)) {
                    this.MsdsUrlField = value;
                    this.RaisePropertyChanged("MsdsUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obsolete {
            get {
                return this.ObsoleteField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsoleteField, value) != true)) {
                    this.ObsoleteField = value;
                    this.RaisePropertyChanged("Obsolete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNo {
            get {
                return this.PartNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNoField, value) != true)) {
                    this.PartNoField = value;
                    this.RaisePropertyChanged("PartNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemCatCentral.CswC3Product.Size[] ProductSize {
            get {
                return this.ProductSizeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSizeField, value) != true)) {
                    this.ProductSizeField = value;
                    this.RaisePropertyChanged("ProductSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductUrl {
            get {
                return this.ProductUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductUrlField, value) != true)) {
                    this.ProductUrlField = value;
                    this.RaisePropertyChanged("ProductUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceName {
            get {
                return this.SourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true)) {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceRowId {
            get {
                return this.SourceRowIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceRowIdField, value) != true)) {
                    this.SourceRowIdField = value;
                    this.RaisePropertyChanged("SourceRowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemCatCentral.CswC3Product.TemplateSlctdExtData[] TemplateSelectedExtensionData {
            get {
                return this.TemplateSelectedExtensionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateSelectedExtensionDataField, value) != true)) {
                    this.TemplateSelectedExtensionDataField = value;
                    this.RaisePropertyChanged("TemplateSelectedExtensionData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeName {
            get {
                return this.TradeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TradeNameField, value) != true)) {
                    this.TradeNameField = value;
                    this.RaisePropertyChanged("TradeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CswC3Product.Size", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
        [System.SerializableAttribute()]
        public partial class Size : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string case_qtyField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string pkg_qtyField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string pkg_qty_uomField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string case_qty {
                get {
                    return this.case_qtyField;
                }
                set {
                    if ((object.ReferenceEquals(this.case_qtyField, value) != true)) {
                        this.case_qtyField = value;
                        this.RaisePropertyChanged("case_qty");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string pkg_qty {
                get {
                    return this.pkg_qtyField;
                }
                set {
                    if ((object.ReferenceEquals(this.pkg_qtyField, value) != true)) {
                        this.pkg_qtyField = value;
                        this.RaisePropertyChanged("pkg_qty");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string pkg_qty_uom {
                get {
                    return this.pkg_qty_uomField;
                }
                set {
                    if ((object.ReferenceEquals(this.pkg_qty_uomField, value) != true)) {
                        this.pkg_qty_uomField = value;
                        this.RaisePropertyChanged("pkg_qty_uom");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CswC3Product.TemplateSlctdExtData", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
        [System.SerializableAttribute()]
        public partial class TemplateSlctdExtData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string attributeField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string valueField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string attribute {
                get {
                    return this.attributeField;
                }
                set {
                    if ((object.ReferenceEquals(this.attributeField, value) != true)) {
                        this.attributeField = value;
                        this.RaisePropertyChanged("attribute");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string value {
                get {
                    return this.valueField;
                }
                set {
                    if ((object.ReferenceEquals(this.valueField, value) != true)) {
                        this.valueField = value;
                        this.RaisePropertyChanged("value");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
    [System.SerializableAttribute()]
    public partial class SampleFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemCatCentral.FaultCode ErrorcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemCatCentral.FaultCode Errorcode {
            get {
                return this.ErrorcodeField;
            }
            set {
                if ((this.ErrorcodeField.Equals(value) != true)) {
                    this.ErrorcodeField = value;
                    this.RaisePropertyChanged("Errorcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultCode", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
    public enum FaultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectParameter = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswC3SearchParams", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswC3SearchParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerLoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchOperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemCatCentral.CswC3SearchParams.SearchFieldType SearchTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessId {
            get {
                return this.AccessIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessIdField, value) != true)) {
                    this.AccessIdField = value;
                    this.RaisePropertyChanged("AccessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLoginName {
            get {
                return this.CustomerLoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerLoginNameField, value) != true)) {
                    this.CustomerLoginNameField = value;
                    this.RaisePropertyChanged("CustomerLoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginPassword {
            get {
                return this.LoginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginPasswordField, value) != true)) {
                    this.LoginPasswordField = value;
                    this.RaisePropertyChanged("LoginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxRows {
            get {
                return this.MaxRowsField;
            }
            set {
                if ((this.MaxRowsField.Equals(value) != true)) {
                    this.MaxRowsField = value;
                    this.RaisePropertyChanged("MaxRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Query {
            get {
                return this.QueryField;
            }
            set {
                if ((object.ReferenceEquals(this.QueryField, value) != true)) {
                    this.QueryField = value;
                    this.RaisePropertyChanged("Query");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SearchOperator {
            get {
                return this.SearchOperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchOperatorField, value) != true)) {
                    this.SearchOperatorField = value;
                    this.RaisePropertyChanged("SearchOperator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemCatCentral.CswC3SearchParams.SearchFieldType SearchTypes {
            get {
                return this.SearchTypesField;
            }
            set {
                if ((this.SearchTypesField.Equals(value) != true)) {
                    this.SearchTypesField = value;
                    this.RaisePropertyChanged("SearchTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceName {
            get {
                return this.SourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true)) {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CswC3SearchParams.SearchFieldType", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii.WebServices")]
        public enum SearchFieldType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CasNo = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CatalogNo = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Formula = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Name = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            TradeName = 4,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            SupplierName = 5,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Structure = 6,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChemCatCentral.Search")]
    public interface Search {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/authenticateUser", ReplyAction="http://tempuri.org/Search/authenticateUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/authenticateUserSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults authenticateUser(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/getDataSources", ReplyAction="http://tempuri.org/Search/getDataSourcesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/getDataSourcesSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults getDataSources(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/getUsers", ReplyAction="http://tempuri.org/Search/getUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/getUsersSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults getUsers(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/editUser", ReplyAction="http://tempuri.org/Search/editUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/editUserSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults editUser(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/deleteUser", ReplyAction="http://tempuri.org/Search/deleteUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/deleteUserSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults deleteUser(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/updateImportStatus", ReplyAction="http://tempuri.org/Search/updateImportStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/updateImportStatusSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults updateImportStatus(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/getProductDetails", ReplyAction="http://tempuri.org/Search/getProductDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/getProductDetailsSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults getProductDetails(ChemSW.Nbt.ChemCatCentral.CswC3SearchParams CswC3SearchParams);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Search/search", ReplyAction="http://tempuri.org/Search/searchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ChemSW.Nbt.ChemCatCentral.SampleFaultException), Action="http://tempuri.org/Search/searchSampleFaultExceptionFault", Name="SampleFaultException", Namespace="http://schemas.datacontract.org/2004/07/c3WebServii")]
        ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults search(ChemSW.Nbt.ChemCatCentral.CswC3SearchParams CswC3SearchParams);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchChannel : ChemSW.Nbt.ChemCatCentral.Search, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchClient : System.ServiceModel.ClientBase<ChemSW.Nbt.ChemCatCentral.Search>, ChemSW.Nbt.ChemCatCentral.Search {
        
        public SearchClient() {
        }
        
        public SearchClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults authenticateUser(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params) {
            return base.Channel.authenticateUser(CswC3Params);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults getDataSources(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params) {
            return base.Channel.getDataSources(CswC3Params);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults getUsers(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params) {
            return base.Channel.getUsers(CswC3Params);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults editUser(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params) {
            return base.Channel.editUser(CswC3Params);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults deleteUser(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params) {
            return base.Channel.deleteUser(CswC3Params);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults updateImportStatus(ChemSW.Nbt.ChemCatCentral.CswC3Params CswC3Params) {
            return base.Channel.updateImportStatus(CswC3Params);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults getProductDetails(ChemSW.Nbt.ChemCatCentral.CswC3SearchParams CswC3SearchParams) {
            return base.Channel.getProductDetails(CswC3SearchParams);
        }
        
        public ChemSW.Nbt.ChemCatCentral.CswRetObjSearchResults search(ChemSW.Nbt.ChemCatCentral.CswC3SearchParams CswC3SearchParams) {
            return base.Channel.search(CswC3SearchParams);
        }
    }
}
