//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbtPrintLib.NbtPublic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcSessionAuthenticateData.Authentication.Request", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    public partial class CswWebSvcSessionAuthenticateDataAuthenticationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMobileField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuppressLogField;
        
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsMobile {
            get {
                return this.IsMobileField;
            }
            set {
                if ((this.IsMobileField.Equals(value) != true)) {
                    this.IsMobileField = value;
                    this.RaisePropertyChanged("IsMobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuppressLog {
            get {
                return this.SuppressLogField;
            }
            set {
                if ((this.SuppressLogField.Equals(value) != true)) {
                    this.SuppressLogField = value;
                    this.RaisePropertyChanged("SuppressLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcReturn", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Returns")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtLabelJobResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtLabelJobUpdateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtLabelPrinterReg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtLabelEpl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtBalanceReturn))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtWebServiceSessionCswNbtAuthReturn))]
    public partial class CswWebSvcReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcSessionAuthenticateDataAuthenticationResponse AuthenticationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcReturnBaseLogging LoggingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcReturnBasePerformance PerformanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcReturnBaseStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcSessionAuthenticateDataAuthenticationResponse Authentication {
            get {
                return this.AuthenticationField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationField, value) != true)) {
                    this.AuthenticationField = value;
                    this.RaisePropertyChanged("Authentication");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcReturnBaseLogging Logging {
            get {
                return this.LoggingField;
            }
            set {
                if ((object.ReferenceEquals(this.LoggingField, value) != true)) {
                    this.LoggingField = value;
                    this.RaisePropertyChanged("Logging");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcReturnBasePerformance Performance {
            get {
                return this.PerformanceField;
            }
            set {
                if ((object.ReferenceEquals(this.PerformanceField, value) != true)) {
                    this.PerformanceField = value;
                    this.RaisePropertyChanged("Performance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcReturnBaseStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcSessionAuthenticateData.Authentication.Response", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    public partial class CswWebSvcSessionAuthenticateDataAuthenticationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticationStatusTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcSessionAuthenticateDataAuthenticationResponse.Expired ExpirationResetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeOutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationStatus {
            get {
                return this.AuthenticationStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationStatusField, value) != true)) {
                    this.AuthenticationStatusField = value;
                    this.RaisePropertyChanged("AuthenticationStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthenticationStatusText {
            get {
                return this.AuthenticationStatusTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticationStatusTextField, value) != true)) {
                    this.AuthenticationStatusTextField = value;
                    this.RaisePropertyChanged("AuthenticationStatusText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcSessionAuthenticateDataAuthenticationResponse.Expired ExpirationReset {
            get {
                return this.ExpirationResetField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpirationResetField, value) != true)) {
                    this.ExpirationResetField = value;
                    this.RaisePropertyChanged("ExpirationReset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOut {
            get {
                return this.TimeOutField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOutField, value) != true)) {
                    this.TimeOutField = value;
                    this.RaisePropertyChanged("TimeOut");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcSessionAuthenticateData.Authentication.Response.Expired", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
        [System.SerializableAttribute()]
        public partial class Expired : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NewPasswordField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string PasswordIdField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string UserIdField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string UserKeyField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string NewPassword {
                get {
                    return this.NewPasswordField;
                }
                set {
                    if ((object.ReferenceEquals(this.NewPasswordField, value) != true)) {
                        this.NewPasswordField = value;
                        this.RaisePropertyChanged("NewPassword");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PasswordId {
                get {
                    return this.PasswordIdField;
                }
                set {
                    if ((object.ReferenceEquals(this.PasswordIdField, value) != true)) {
                        this.PasswordIdField = value;
                        this.RaisePropertyChanged("PasswordId");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string UserId {
                get {
                    return this.UserIdField;
                }
                set {
                    if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                        this.UserIdField = value;
                        this.RaisePropertyChanged("UserId");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string UserKey {
                get {
                    return this.UserKeyField;
                }
                set {
                    if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                        this.UserKeyField = value;
                        this.RaisePropertyChanged("UserKey");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcReturnBase.Logging", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    public partial class CswWebSvcReturnBaseLogging : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogglyInputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIdField, value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogLevel {
            get {
                return this.LogLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.LogLevelField, value) != true)) {
                    this.LogLevelField = value;
                    this.RaisePropertyChanged("LogLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogglyInput {
            get {
                return this.LogglyInputField;
            }
            set {
                if ((object.ReferenceEquals(this.LogglyInputField, value) != true)) {
                    this.LogglyInputField = value;
                    this.RaisePropertyChanged("LogglyInput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Server {
            get {
                return this.ServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerField, value) != true)) {
                    this.ServerField = value;
                    this.RaisePropertyChanged("Server");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcReturnBase.Performance", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    public partial class CswWebSvcReturnBasePerformance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DbCommitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DbDeinitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DbInitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DbQueryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ServerInitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ServerTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TreeLoaderSqlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DbCommit {
            get {
                return this.DbCommitField;
            }
            set {
                if ((this.DbCommitField.Equals(value) != true)) {
                    this.DbCommitField = value;
                    this.RaisePropertyChanged("DbCommit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DbDeinit {
            get {
                return this.DbDeinitField;
            }
            set {
                if ((this.DbDeinitField.Equals(value) != true)) {
                    this.DbDeinitField = value;
                    this.RaisePropertyChanged("DbDeinit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DbInit {
            get {
                return this.DbInitField;
            }
            set {
                if ((this.DbInitField.Equals(value) != true)) {
                    this.DbInitField = value;
                    this.RaisePropertyChanged("DbInit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DbQuery {
            get {
                return this.DbQueryField;
            }
            set {
                if ((this.DbQueryField.Equals(value) != true)) {
                    this.DbQueryField = value;
                    this.RaisePropertyChanged("DbQuery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ServerInit {
            get {
                return this.ServerInitField;
            }
            set {
                if ((this.ServerInitField.Equals(value) != true)) {
                    this.ServerInitField = value;
                    this.RaisePropertyChanged("ServerInit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ServerTotal {
            get {
                return this.ServerTotalField;
            }
            set {
                if ((this.ServerTotalField.Equals(value) != true)) {
                    this.ServerTotalField = value;
                    this.RaisePropertyChanged("ServerTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TreeLoaderSql {
            get {
                return this.TreeLoaderSqlField;
            }
            set {
                if ((this.TreeLoaderSqlField.Equals(value) != true)) {
                    this.TreeLoaderSqlField = value;
                    this.RaisePropertyChanged("TreeLoaderSql");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcReturnBase.Status", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    public partial class CswWebSvcReturnBaseStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcReturnBaseErrorMessage[] ErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcReturnBaseErrorMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcReturnBaseErrorMessage[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcReturnBaseErrorMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtLabelJobResponse", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class CswNbtLabelJobResponse : NbtPrintLib.NbtPublic.CswWebSvcReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobOwnerField;
        
        private int LabelCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainingJobCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobKey {
            get {
                return this.JobKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.JobKeyField, value) != true)) {
                    this.JobKeyField = value;
                    this.RaisePropertyChanged("JobKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobNo {
            get {
                return this.JobNoField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNoField, value) != true)) {
                    this.JobNoField = value;
                    this.RaisePropertyChanged("JobNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobOwner {
            get {
                return this.JobOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.JobOwnerField, value) != true)) {
                    this.JobOwnerField = value;
                    this.RaisePropertyChanged("JobOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LabelCount {
            get {
                return this.LabelCountField;
            }
            set {
                if ((this.LabelCountField.Equals(value) != true)) {
                    this.LabelCountField = value;
                    this.RaisePropertyChanged("LabelCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelData {
            get {
                return this.LabelDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelDataField, value) != true)) {
                    this.LabelDataField = value;
                    this.RaisePropertyChanged("LabelData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelName {
            get {
                return this.LabelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelNameField, value) != true)) {
                    this.LabelNameField = value;
                    this.RaisePropertyChanged("LabelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrinterName {
            get {
                return this.PrinterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterNameField, value) != true)) {
                    this.PrinterNameField = value;
                    this.RaisePropertyChanged("PrinterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainingJobCount {
            get {
                return this.RemainingJobCountField;
            }
            set {
                if ((this.RemainingJobCountField.Equals(value) != true)) {
                    this.RemainingJobCountField = value;
                    this.RaisePropertyChanged("RemainingJobCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtLabelJobUpdateResponse", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class CswNbtLabelJobUpdateResponse : NbtPrintLib.NbtPublic.CswWebSvcReturn {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtLabelPrinterReg", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtLabelPrinterReg : NbtPrintLib.NbtPublic.CswWebSvcReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrinterKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrinterKey {
            get {
                return this.PrinterKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterKeyField, value) != true)) {
                    this.PrinterKeyField = value;
                    this.RaisePropertyChanged("PrinterKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtLabelEpl", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtLabelEpl : NbtPrintLib.NbtPublic.CswWebSvcReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.NbtPrintLabelResponseEpl DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.NbtPrintLabelResponseEpl Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtBalanceReturn", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtBalanceReturn : NbtPrintLib.NbtPublic.CswWebSvcReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswNbtBalanceData DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswNbtBalanceData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtWebServiceSession.CswNbtAuthReturn", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtWebServiceSessionCswNbtAuthReturn : NbtPrintLib.NbtPublic.CswWebSvcReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswNbtWebServiceSessionCswNbtUserDefaultsData DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswNbtWebServiceSessionCswNbtUserDefaultsData Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtWebServiceSession.CswNbtUserDefaultsData", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtWebServiceSessionCswNbtUserDefaultsData : NbtPrintLib.NbtPublic.CswWebSvcReturnBaseData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultBalanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultLocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultPrinterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSDateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JSTimeFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JurisdictionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswNbtWebServiceSessionSchemaDetails SchemaDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkUnitIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFormat {
            get {
                return this.DateFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFormatField, value) != true)) {
                    this.DateFormatField = value;
                    this.RaisePropertyChanged("DateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultBalanceId {
            get {
                return this.DefaultBalanceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultBalanceIdField, value) != true)) {
                    this.DefaultBalanceIdField = value;
                    this.RaisePropertyChanged("DefaultBalanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultLocationId {
            get {
                return this.DefaultLocationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultLocationIdField, value) != true)) {
                    this.DefaultLocationIdField = value;
                    this.RaisePropertyChanged("DefaultLocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultPrinterId {
            get {
                return this.DefaultPrinterIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultPrinterIdField, value) != true)) {
                    this.DefaultPrinterIdField = value;
                    this.RaisePropertyChanged("DefaultPrinterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="JS Date Format")]
        public string JSDateFormat {
            get {
                return this.JSDateFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.JSDateFormatField, value) != true)) {
                    this.JSDateFormatField = value;
                    this.RaisePropertyChanged("JSDateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="JS Time Format")]
        public string JSTimeFormat {
            get {
                return this.JSTimeFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.JSTimeFormatField, value) != true)) {
                    this.JSTimeFormatField = value;
                    this.RaisePropertyChanged("JSTimeFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JurisdictionId {
            get {
                return this.JurisdictionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.JurisdictionIdField, value) != true)) {
                    this.JurisdictionIdField = value;
                    this.RaisePropertyChanged("JurisdictionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswNbtWebServiceSessionSchemaDetails SchemaData {
            get {
                return this.SchemaDataField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemaDataField, value) != true)) {
                    this.SchemaDataField = value;
                    this.RaisePropertyChanged("SchemaData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeFormat {
            get {
                return this.TimeFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeFormatField, value) != true)) {
                    this.TimeFormatField = value;
                    this.RaisePropertyChanged("TimeFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkUnitId {
            get {
                return this.WorkUnitIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkUnitIdField, value) != true)) {
                    this.WorkUnitIdField = value;
                    this.RaisePropertyChanged("WorkUnitId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcReturnBase.ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    public partial class CswWebSvcReturnBaseErrorMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detail {
            get {
                return this.DetailField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailField, value) != true)) {
                    this.DetailField = value;
                    this.RaisePropertyChanged("Detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowError {
            get {
                return this.ShowErrorField;
            }
            set {
                if ((this.ShowErrorField.Equals(value) != true)) {
                    this.ShowErrorField = value;
                    this.RaisePropertyChanged("ShowError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NbtPrintLabel.Response.Epl", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class NbtPrintLabelResponseEpl : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.PrintLabel[] LabelsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.PrintLabel[] Labels {
            get {
                return this.LabelsField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelsField, value) != true)) {
                    this.LabelsField = value;
                    this.RaisePropertyChanged("Labels");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintLabel", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class PrintLabel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EplTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.PrintLabel.Picto[] PictosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EplText {
            get {
                return this.EplTextField;
            }
            set {
                if ((object.ReferenceEquals(this.EplTextField, value) != true)) {
                    this.EplTextField = value;
                    this.RaisePropertyChanged("EplText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.PrintLabel.Picto[] Pictos {
            get {
                return this.PictosField;
            }
            set {
                if ((object.ReferenceEquals(this.PictosField, value) != true)) {
                    this.PictosField = value;
                    this.RaisePropertyChanged("Pictos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetIdField, value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetName {
            get {
                return this.TargetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetNameField, value) != true)) {
                    this.TargetNameField = value;
                    this.RaisePropertyChanged("TargetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PrintLabel.Picto", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
        [System.SerializableAttribute()]
        public partial class Picto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FileNameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string FileURLField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FileName {
                get {
                    return this.FileNameField;
                }
                set {
                    if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                        this.FileNameField = value;
                        this.RaisePropertyChanged("FileName");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string FileURL {
                get {
                    return this.FileURLField;
                }
                set {
                    if ((object.ReferenceEquals(this.FileURLField, value) != true)) {
                        this.FileURLField = value;
                        this.RaisePropertyChanged("FileURL");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtBalanceData", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtBalanceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.SerialBalance[] BalanceListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.BalanceConfiguration[] ConfigurationListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.SerialBalance[] BalanceList {
            get {
                return this.BalanceListField;
            }
            set {
                if ((object.ReferenceEquals(this.BalanceListField, value) != true)) {
                    this.BalanceListField = value;
                    this.RaisePropertyChanged("BalanceList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.BalanceConfiguration[] ConfigurationList {
            get {
                return this.ConfigurationListField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationListField, value) != true)) {
                    this.ConfigurationListField = value;
                    this.RaisePropertyChanged("ConfigurationList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SerialBalance", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic")]
    [System.SerializableAttribute()]
    public partial class SerialBalance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ConfigurationField;
        
        private double CurrentWeightField;
        
        private string DeviceDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        private string ManufacturerField;
        
        private string NbtNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NodeIdField;
        
        private bool OperationalField;
        
        private string UnitOfMeasurementField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Configuration {
            get {
                return this.ConfigurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationField, value) != true)) {
                    this.ConfigurationField = value;
                    this.RaisePropertyChanged("Configuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double CurrentWeight {
            get {
                return this.CurrentWeightField;
            }
            set {
                if ((this.CurrentWeightField.Equals(value) != true)) {
                    this.CurrentWeightField = value;
                    this.RaisePropertyChanged("CurrentWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DeviceDescription {
            get {
                return this.DeviceDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceDescriptionField, value) != true)) {
                    this.DeviceDescriptionField = value;
                    this.RaisePropertyChanged("DeviceDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NbtName {
            get {
                return this.NbtNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NbtNameField, value) != true)) {
                    this.NbtNameField = value;
                    this.RaisePropertyChanged("NbtName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NodeId {
            get {
                return this.NodeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeIdField, value) != true)) {
                    this.NodeIdField = value;
                    this.RaisePropertyChanged("NodeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Operational {
            get {
                return this.OperationalField;
            }
            set {
                if ((this.OperationalField.Equals(value) != true)) {
                    this.OperationalField = value;
                    this.RaisePropertyChanged("Operational");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UnitOfMeasurement {
            get {
                return this.UnitOfMeasurementField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitOfMeasurementField, value) != true)) {
                    this.UnitOfMeasurementField = value;
                    this.RaisePropertyChanged("UnitOfMeasurement");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceConfiguration", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic")]
    [System.SerializableAttribute()]
    public partial class BalanceConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BaudRateField;
        
        private int DataBitsField;
        
        private string HandshakeField;
        
        private string NameField;
        
        private string ParityBitField;
        
        private string RequestFormatField;
        
        private string ResponseFormatField;
        
        private string StopBitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BaudRate {
            get {
                return this.BaudRateField;
            }
            set {
                if ((this.BaudRateField.Equals(value) != true)) {
                    this.BaudRateField = value;
                    this.RaisePropertyChanged("BaudRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DataBits {
            get {
                return this.DataBitsField;
            }
            set {
                if ((this.DataBitsField.Equals(value) != true)) {
                    this.DataBitsField = value;
                    this.RaisePropertyChanged("DataBits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Handshake {
            get {
                return this.HandshakeField;
            }
            set {
                if ((object.ReferenceEquals(this.HandshakeField, value) != true)) {
                    this.HandshakeField = value;
                    this.RaisePropertyChanged("Handshake");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ParityBit {
            get {
                return this.ParityBitField;
            }
            set {
                if ((object.ReferenceEquals(this.ParityBitField, value) != true)) {
                    this.ParityBitField = value;
                    this.RaisePropertyChanged("ParityBit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string RequestFormat {
            get {
                return this.RequestFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestFormatField, value) != true)) {
                    this.RequestFormatField = value;
                    this.RaisePropertyChanged("RequestFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResponseFormat {
            get {
                return this.ResponseFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseFormatField, value) != true)) {
                    this.ResponseFormatField = value;
                    this.RaisePropertyChanged("ResponseFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string StopBits {
            get {
                return this.StopBitsField;
            }
            set {
                if ((object.ReferenceEquals(this.StopBitsField, value) != true)) {
                    this.StopBitsField = value;
                    this.RaisePropertyChanged("StopBits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswWebSvcReturnBase.Data", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.WebSvc")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NbtPrintLib.NbtPublic.CswNbtWebServiceSessionCswNbtUserDefaultsData))]
    public partial class CswWebSvcReturnBaseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SucceededField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succeeded {
            get {
                return this.SucceededField;
            }
            set {
                if ((this.SucceededField.Equals(value) != true)) {
                    this.SucceededField = value;
                    this.RaisePropertyChanged("Succeeded");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtWebServiceSession.SchemaDetails", Namespace="http://schemas.datacontract.org/2004/07/ChemSW.Nbt.WebServices")]
    [System.SerializableAttribute()]
    public partial class CswNbtWebServiceSessionSchemaDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NbtPrintLib.NbtPublic.CswWebSvcReturnBaseErrorMessage ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CorrectVersion {
            get {
                return this.CorrectVersionField;
            }
            set {
                if ((this.CorrectVersionField.Equals(value) != true)) {
                    this.CorrectVersionField = value;
                    this.RaisePropertyChanged("CorrectVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NbtPrintLib.NbtPublic.CswWebSvcReturnBaseErrorMessage ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LabelPrinter", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class LabelPrinter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        private string LpcNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LpcName {
            get {
                return this.LpcNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LpcNameField, value) != true)) {
                    this.LpcNameField = value;
                    this.RaisePropertyChanged("LpcName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtLabelJobRequest", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class CswNbtLabelJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PrinterKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PrinterKey {
            get {
                return this.PrinterKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrinterKeyField, value) != true)) {
                    this.PrinterKeyField = value;
                    this.RaisePropertyChanged("PrinterKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NbtPrintLabel.Request.Get", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class NbtPrintLabelRequestGet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelId {
            get {
                return this.LabelIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelIdField, value) != true)) {
                    this.LabelIdField = value;
                    this.RaisePropertyChanged("LabelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Params {
            get {
                return this.ParamsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamsField, value) != true)) {
                    this.ParamsField = value;
                    this.RaisePropertyChanged("Params");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetId {
            get {
                return this.TargetIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetIdField, value) != true)) {
                    this.TargetIdField = value;
                    this.RaisePropertyChanged("TargetId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CswNbtLabelJobUpdateRequest", Namespace="http://schemas.datacontract.org/2004/07/NbtWebApp.WebSvc.Logic.Labels")]
    [System.SerializableAttribute()]
    public partial class CswNbtLabelJobUpdateRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        private string JobKeyField;
        
        private bool SucceededField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string JobKey {
            get {
                return this.JobKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.JobKeyField, value) != true)) {
                    this.JobKeyField = value;
                    this.RaisePropertyChanged("JobKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Succeeded {
            get {
                return this.SucceededField;
            }
            set {
                if ((this.SucceededField.Equals(value) != true)) {
                    this.SucceededField = value;
                    this.RaisePropertyChanged("Succeeded");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="NbtWebApp", ConfigurationName="NbtPublic.NbtPublic")]
    public interface NbtPublic {
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/SessionInit", ReplyAction="NbtWebApp/NbtPublic/SessionInitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/SessionInitFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtWebServiceSessionCswNbtAuthReturn SessionInit(NbtPrintLib.NbtPublic.CswWebSvcSessionAuthenticateDataAuthenticationRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/SessionEnd", ReplyAction="NbtWebApp/NbtPublic/SessionEndResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/SessionEndFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        void SessionEnd();
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/LpcRegister", ReplyAction="NbtWebApp/NbtPublic/LpcRegisterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/LpcRegisterFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtLabelPrinterReg LpcRegister(NbtPrintLib.NbtPublic.LabelPrinter Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/LpcGetNextJob", ReplyAction="NbtWebApp/NbtPublic/LpcGetNextJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/LpcGetNextJobFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtLabelJobResponse LpcGetNextJob(NbtPrintLib.NbtPublic.CswNbtLabelJobRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/LpcGetLabel", ReplyAction="NbtWebApp/NbtPublic/LpcGetLabelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/LpcGetLabelFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtLabelEpl LpcGetLabel(NbtPrintLib.NbtPublic.NbtPrintLabelRequestGet Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/LpcUpdateJob", ReplyAction="NbtWebApp/NbtPublic/LpcUpdateJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/LpcUpdateJobFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtLabelJobUpdateResponse LpcUpdateJob(NbtPrintLib.NbtPublic.CswNbtLabelJobUpdateRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/UpdateBalanceData", ReplyAction="NbtWebApp/NbtPublic/UpdateBalanceDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/UpdateBalanceDataFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        void UpdateBalanceData(NbtPrintLib.NbtPublic.SerialBalance Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/ListBalanceConfigurations", ReplyAction="NbtWebApp/NbtPublic/ListBalanceConfigurationsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/ListBalanceConfigurationsFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtBalanceReturn ListBalanceConfigurations();
        
        [System.ServiceModel.OperationContractAttribute(Action="NbtWebApp/NbtPublic/registerBalanceConfiguration", ReplyAction="NbtWebApp/NbtPublic/registerBalanceConfigurationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="NbtWebApp/NbtPublic/registerBalanceConfigurationFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        NbtPrintLib.NbtPublic.CswNbtBalanceReturn registerBalanceConfiguration(NbtPrintLib.NbtPublic.BalanceConfiguration Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NbtPublicChannel : NbtPrintLib.NbtPublic.NbtPublic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NbtPublicClient : System.ServiceModel.ClientBase<NbtPrintLib.NbtPublic.NbtPublic>, NbtPrintLib.NbtPublic.NbtPublic {
        
        public NbtPublicClient() {
        }
        
        public NbtPublicClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NbtPublicClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NbtPublicClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NbtPublicClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NbtPrintLib.NbtPublic.CswNbtWebServiceSessionCswNbtAuthReturn SessionInit(NbtPrintLib.NbtPublic.CswWebSvcSessionAuthenticateDataAuthenticationRequest Request) {
            return base.Channel.SessionInit(Request);
        }
        
        public void SessionEnd() {
            base.Channel.SessionEnd();
        }
        
        public NbtPrintLib.NbtPublic.CswNbtLabelPrinterReg LpcRegister(NbtPrintLib.NbtPublic.LabelPrinter Request) {
            return base.Channel.LpcRegister(Request);
        }
        
        public NbtPrintLib.NbtPublic.CswNbtLabelJobResponse LpcGetNextJob(NbtPrintLib.NbtPublic.CswNbtLabelJobRequest Request) {
            return base.Channel.LpcGetNextJob(Request);
        }
        
        public NbtPrintLib.NbtPublic.CswNbtLabelEpl LpcGetLabel(NbtPrintLib.NbtPublic.NbtPrintLabelRequestGet Request) {
            return base.Channel.LpcGetLabel(Request);
        }
        
        public NbtPrintLib.NbtPublic.CswNbtLabelJobUpdateResponse LpcUpdateJob(NbtPrintLib.NbtPublic.CswNbtLabelJobUpdateRequest Request) {
            return base.Channel.LpcUpdateJob(Request);
        }
        
        public void UpdateBalanceData(NbtPrintLib.NbtPublic.SerialBalance Request) {
            base.Channel.UpdateBalanceData(Request);
        }
        
        public NbtPrintLib.NbtPublic.CswNbtBalanceReturn ListBalanceConfigurations() {
            return base.Channel.ListBalanceConfigurations();
        }
        
        public NbtPrintLib.NbtPublic.CswNbtBalanceReturn registerBalanceConfiguration(NbtPrintLib.NbtPublic.BalanceConfiguration Request) {
            return base.Channel.registerBalanceConfiguration(Request);
        }
    }
}
