-- ****** Object: Table NBT.ACTIONS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "ACTIONS" (
  "ACTIONID" NUMBER(12,0) NOT NULL,
  "ACTIONNAME" VARCHAR2(40 BYTE) NULL,
  "SHOWINLIST" CHAR(1 BYTE) NULL,
  "URL" VARCHAR2(100 BYTE) NULL,
  "CATEGORY" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "ACTIONID_PK"
  ON "ACTIONS" ( 
    "ACTIONID");
ALTER TABLE "ACTIONS" ADD ( 
  CONSTRAINT "ACTIONID_PK" 
    PRIMARY KEY ( "ACTIONID") 
    USING INDEX "ACTIONID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.AUDIT_TRANSACTIONS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "AUDIT_TRANSACTIONS" (
  "AUDITTRANSACTIONID" NUMBER(12,0) NOT NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "AUDITEVENTNAME" VARCHAR2(50 BYTE) NULL,
  "ESIGREASON" VARCHAR2(50 BYTE) NULL,
  "ESIGUSERNAME" VARCHAR2(50 BYTE) NULL,
  "ESIGUSERPASSWORD" VARCHAR2(50 BYTE) NULL,
  "TRANSACTIONUSERNAME" VARCHAR2(50 BYTE) NULL,
  "TRANSACTIONFIRSTNAME" VARCHAR2(50 BYTE) NULL,
  "TRANSACTIONLASTNAME" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047568"
  ON "AUDIT_TRANSACTIONS" ( 
    "AUDITTRANSACTIONID");
ALTER TABLE "AUDIT_TRANSACTIONS" ADD ( 
  CONSTRAINT "SYS_C0047568" 
    PRIMARY KEY ( "AUDITTRANSACTIONID") 
    USING INDEX "SYS_C0047568" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.CONFIGURATION_VARIABLES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "CONFIGURATION_VARIABLES" (
  "CONFIGURATIONVARIABLEID" NUMBER(12,0) NOT NULL,
  "DELETED" CHAR(1 BYTE) NULL,
  "DESCRIPTION" VARCHAR2(100 BYTE) NULL,
  "ISSYSTEM" CHAR(1 BYTE) NULL,
  "VARIABLENAME" VARCHAR2(100 BYTE) NULL,
  "VARIABLEVALUE" VARCHAR2(1000 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "CONFIGURATIONVARIABLEID_PK"
  ON "CONFIGURATION_VARIABLES" ( 
    "CONFIGURATIONVARIABLEID");
ALTER TABLE "CONFIGURATION_VARIABLES" ADD ( 
  CONSTRAINT "CONFIGURATIONVARIABLEID_PK" 
    PRIMARY KEY ( "CONFIGURATIONVARIABLEID") 
    USING INDEX "CONFIGURATIONVARIABLEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.DATA_DICTIONARY Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "DATA_DICTIONARY" (
  "ALLOWNONEXISTENTFKREF" CHAR(1 BYTE) NULL,
  "COLUMNNAME" VARCHAR2(50 BYTE) NULL,
  "COLUMNTYPE" VARCHAR2(10 BYTE) NULL,
  "DATATYPESIZE" NUMBER(12,0) NULL,
  "DBLPRECISION" NUMBER(12,0) NULL,
  "DEFAULTVALUE" VARCHAR2(50 BYTE) NULL,
  "DELETED" CHAR(1 BYTE) NULL,
  "DESCRIPTION" VARCHAR2(1024 BYTE) NULL,
  "FOREIGNKEYCOLUMN" VARCHAR2(50 BYTE) NULL,
  "FOREIGNKEYTABLE" VARCHAR2(50 BYTE) NULL,
  "ISVIEW" CHAR(1 BYTE) NULL,
  "LOGICALDELETE" CHAR(1 BYTE) NULL,
  "LOWERRANGEVALUE" VARCHAR2(50 BYTE) NULL,
  "LOWERRANGEVALUEINCLUSIVE" CHAR(1 BYTE) NULL,
  "PORTABLEDATATYPE" VARCHAR2(50 BYTE) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "REQUIRED" CHAR(1 BYTE) NULL,
  "TABLECOLID" NUMBER(12,0) NOT NULL,
  "TABLENAME" VARCHAR2(50 BYTE) NULL,
  "UNIQUETYPE" VARCHAR2(20 BYTE) NULL,
  "UPERRANGEVALUEINCLUSIVE" CHAR(1 BYTE) NULL,
  "UPPERRANGEVALUE" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    INITIAL 131072
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "TABLECOLID_PK"
  ON "DATA_DICTIONARY" ( 
    "TABLECOLID");
ALTER TABLE "DATA_DICTIONARY" ADD ( 
  CONSTRAINT "TABLECOLID_PK" 
    PRIMARY KEY ( "TABLECOLID") 
    USING INDEX "TABLECOLID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.FIELD_TYPES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "FIELD_TYPES" (
  "AUDITFLAG" CHAR(1 BYTE) NULL,
  "DATATYPE" VARCHAR2(50 BYTE) NULL,
  "DELETED" CHAR(1 BYTE) NULL,
  "FIELDPRECISION" NUMBER(12,0) NULL,
  "FIELDTYPE" VARCHAR2(50 BYTE) NULL,
  "FIELDTYPEID" NUMBER(12,0) NOT NULL,
  "MASK" VARCHAR2(50 BYTE) NULL,
  "SEARCHABLE" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "FIELDTYPEID_PK"
  ON "FIELD_TYPES" ( 
    "FIELDTYPEID");
ALTER TABLE "FIELD_TYPES" ADD ( 
  CONSTRAINT "FIELDTYPEID_PK" 
    PRIMARY KEY ( "FIELDTYPEID") 
    USING INDEX "FIELDTYPEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.FIELD_TYPES_SUBFIELDS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "FIELD_TYPES_SUBFIELDS" (
  "FTSUBFIELDID" NUMBER(12,0) NOT NULL,
  "FIELDTYPEID" NUMBER(12,0) NULL,
  "PROPCOLNAME" VARCHAR2(20 BYTE) NULL,
  "REPORTABLE" CHAR(1 BYTE) NULL,
  "IS_DEFAULT" CHAR(1 BYTE) NULL,
  "SUBFIELDNAME" VARCHAR2(20 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047570"
  ON "FIELD_TYPES_SUBFIELDS" ( 
    "FTSUBFIELDID");
ALTER TABLE "FIELD_TYPES_SUBFIELDS" ADD ( 
  CONSTRAINT "SYS_C0047570" 
    PRIMARY KEY ( "FTSUBFIELDID") 
    USING INDEX "SYS_C0047570" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.FKEY_DEFINITIONS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "FKEY_DEFINITIONS" (
  "DELETED" CHAR(1 BYTE) NULL,
  "FKEYDEFID" NUMBER(12,0) NOT NULL,
  "FKEYNAME" VARCHAR2(80 BYTE) NULL,
  "SQL" CLOB NULL,
  "PK_TABLE" VARCHAR2(50 BYTE) NULL,
  "PK_COLUMN" VARCHAR2(50 BYTE) NULL,
  "REF_TABLE" VARCHAR2(50 BYTE) NULL,
  "REF_COLUMN" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "FKEYDEFID_PK"
  ON "FKEY_DEFINITIONS" ( 
    "FKEYDEFID");
ALTER TABLE "FKEY_DEFINITIONS" ADD ( 
  CONSTRAINT "FKEYDEFID_PK" 
    PRIMARY KEY ( "FKEYDEFID") 
    USING INDEX "FKEYDEFID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.JCT_DD_NTP Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "JCT_DD_NTP" (
  "JCTDDNTPID" NUMBER(12,0) NOT NULL,
  "DATADICTIONARYID" NUMBER(12,0) NULL,
  "NODETYPEPROPID" NUMBER(12,0) NULL,
  "SUBFIELDNAME" VARCHAR2(20 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047546"
  ON "JCT_DD_NTP" ( 
    "JCTDDNTPID");
ALTER TABLE "JCT_DD_NTP" ADD ( 
  CONSTRAINT "SYS_C0047546" 
    PRIMARY KEY ( "JCTDDNTPID") 
    USING INDEX "SYS_C0047546" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.JCT_MODULES_ACTIONS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "JCT_MODULES_ACTIONS" (
  "JCTMODULEACTIONID" NUMBER(12,0) NOT NULL,
  "ACTIONID" NUMBER(12,0) NULL,
  "MODULEID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  CONSTRAINT "JMA_ACTIONID_FK" 
    FOREIGN KEY ( "ACTIONID")
       REFERENCES "ACTIONS" ( "ACTIONID") 
    ENABLE 
    VALIDATE,
  CONSTRAINT "JMA_MODULEID_FK" 
    FOREIGN KEY ( "MODULEID")
       REFERENCES "MODULES" ( "MODULEID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "JCTMODULEACTIONID_PK"
  ON "JCT_MODULES_ACTIONS" ( 
    "JCTMODULEACTIONID");
ALTER TABLE "JCT_MODULES_ACTIONS" ADD ( 
  CONSTRAINT "JCTMODULEACTIONID_PK" 
    PRIMARY KEY ( "JCTMODULEACTIONID") 
    USING INDEX "JCTMODULEACTIONID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.JCT_MODULES_NODETYPES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "JCT_MODULES_NODETYPES" (
  "JCTMODULENODETYPEID" NUMBER(12,0) NOT NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "MODULEID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047548"
  ON "JCT_MODULES_NODETYPES" ( 
    "JCTMODULENODETYPEID");
ALTER TABLE "JCT_MODULES_NODETYPES" ADD ( 
  CONSTRAINT "SYS_C0047548" 
    PRIMARY KEY ( "JCTMODULENODETYPEID") 
    USING INDEX "SYS_C0047548" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.JCT_MODULES_OBJECTCLASS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "JCT_MODULES_OBJECTCLASS" (
  "DELETED" CHAR(1 BYTE) NULL,
  "JCTMODULEOBJECTCLASSID" NUMBER(12,0) NOT NULL,
  "MODULEID" NUMBER(12,0) NULL,
  "OBJECTCLASSID" NUMBER(12,0) NULL,
  CONSTRAINT "JMO_OBJECTCLASSID_FK" 
    FOREIGN KEY ( "OBJECTCLASSID")
       REFERENCES "OBJECT_CLASS" ( "OBJECTCLASSID") 
    ENABLE 
    VALIDATE,
  CONSTRAINT "JMO_MODULEID_FK" 
    FOREIGN KEY ( "MODULEID")
       REFERENCES "MODULES" ( "MODULEID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "JCTMODULEOBJECTCLASSID_PK"
  ON "JCT_MODULES_OBJECTCLASS" ( 
    "JCTMODULEOBJECTCLASSID");
ALTER TABLE "JCT_MODULES_OBJECTCLASS" ADD ( 
  CONSTRAINT "JCTMODULEOBJECTCLASSID_PK" 
    PRIMARY KEY ( "JCTMODULEOBJECTCLASSID") 
    USING INDEX "JCTMODULEOBJECTCLASSID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.JCT_NODES_PROPS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "JCT_NODES_PROPS" (
  "FIELD1" VARCHAR2(255 BYTE) NULL,
  "FIELD2" VARCHAR2(255 BYTE) NULL,
  "FIELD3" VARCHAR2(255 BYTE) NULL,
  "JCTNODEPROPID" NUMBER(12,0) NOT NULL,
  "NODEID" NUMBER(12,0) NULL,
  "NODETYPEPROPID" NUMBER(12,0) NULL,
  "FIELD1_FK" NUMBER(12,0) NULL,
  "GESTALT" CLOB NULL,
  "FIELD4" VARCHAR2(255 BYTE) NULL,
  "FIELD5" VARCHAR2(255 BYTE) NULL,
  "BLOBDATA" BLOB NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "PENDINGUPDATE" CHAR(1 BYTE) NULL,
  "CLOBDATA" CLOB NULL,
  "NODEIDTABLENAME" VARCHAR2(50 BYTE) NULL,
  "FIELD1_DATE" DATE NULL,
  "FIELD1_NUMERIC" NUMBER(15,6) NULL,
  "FIELD2_DATE" DATE NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "FIELD2_NUMERIC" NUMBER(15,6) NULL,
  "GESTALTSEARCH" VARCHAR2(512 BYTE) NULL,
  "HIDDEN" CHAR(1 BYTE) NULL,
  CONSTRAINT "JNP_NODETYPEPROPID_FK" 
    FOREIGN KEY ( "NODETYPEPROPID")
       REFERENCES "NODETYPE_PROPS" ( "NODETYPEPROPID") 
    ENABLE 
    VALIDATE,
  CONSTRAINT "JNP_NODEID_FK" 
    FOREIGN KEY ( "NODEID")
       REFERENCES "NODES" ( "NODEID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    INITIAL 131072
    NEXT 1048576 ) ;
CREATE INDEX "JCT9"
  ON "JCT_NODES_PROPS" ( 
    "NODETYPEPROPID", 
    "GESTALTSEARCH");
CREATE INDEX "JCT8"
  ON "JCT_NODES_PROPS" ( 
    "NODEID", 
    "NODETYPEPROPID", 
    "JCTNODEPROPID");
CREATE INDEX "JCT7"
  ON "JCT_NODES_PROPS" ( 
    "JCTNODEPROPID", 
    "NODETYPEPROPID", 
    "NODEID", 
    "FIELD1");
CREATE INDEX "JCT6"
  ON "JCT_NODES_PROPS" ( 
    "FIELD1_FK");
CREATE INDEX "JCT5"
  ON "JCT_NODES_PROPS" ( 
    "JCTNODEPROPID", 
    "NODEID", 
    "NODETYPEPROPID", 
    "FIELD1_FK");
CREATE INDEX "JCT4"
  ON "JCT_NODES_PROPS" ( 
    "NODETYPEPROPID", 
    "NODEID");
CREATE INDEX "JCT3"
  ON "JCT_NODES_PROPS" ( 
    "NODEID", 
    "NODETYPEPROPID");
CREATE INDEX "JCT2"
  ON "JCT_NODES_PROPS" ( 
    "NODETYPEPROPID");
CREATE INDEX "JCT1"
  ON "JCT_NODES_PROPS" ( 
    "NODEID");
CREATE UNIQUE INDEX "JCTNODEPROPID_PK"
  ON "JCT_NODES_PROPS" ( 
    "JCTNODEPROPID");
ALTER TABLE "JCT_NODES_PROPS" ADD ( 
  CONSTRAINT "JCTNODEPROPID_PK" 
    PRIMARY KEY ( "JCTNODEPROPID") 
    USING INDEX "JCTNODEPROPID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.JCT_NODES_PROPS_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "JCT_NODES_PROPS_AUDIT" (
  "FIELD1" VARCHAR2(255 BYTE) NULL,
  "FIELD2" VARCHAR2(255 BYTE) NULL,
  "FIELD3" VARCHAR2(255 BYTE) NULL,
  "JCTNODESPROPSAUDITID" NUMBER(12,0) NOT NULL,
  "NODEID" NUMBER(12,0) NULL,
  "NODETYPEPROPID" NUMBER(12,0) NULL,
  "FIELD1_FK" NUMBER(12,0) NULL,
  "GESTALT" CLOB NULL,
  "FIELD4" VARCHAR2(255 BYTE) NULL,
  "FIELD5" VARCHAR2(255 BYTE) NULL,
  "BLOBDATA" BLOB NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "PENDINGUPDATE" CHAR(1 BYTE) NULL,
  "CLOBDATA" CLOB NULL,
  "NODEIDTABLENAME" VARCHAR2(50 BYTE) NULL,
  "FIELD1_DATE" DATE NULL,
  "FIELD1_NUMERIC" NUMBER(15,6) NULL,
  "FIELD2_DATE" DATE NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "JCTNODEPROPID" NUMBER(12,0) NULL,
  "FIELD2_NUMERIC" NUMBER(15,6) NULL,
  "GESTALTSEARCH" VARCHAR2(512 BYTE) NULL,
  "HIDDEN" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.LICENSE Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "LICENSE" (
  "LICENSEID" NUMBER(12,0) NOT NULL,
  "LICENSETXT" CLOB NULL,
  "ACTIVEDATE" DATE NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047574"
  ON "LICENSE" ( 
    "LICENSEID");
ALTER TABLE "LICENSE" ADD ( 
  CONSTRAINT "SYS_C0047574" 
    PRIMARY KEY ( "LICENSEID") 
    USING INDEX "SYS_C0047574" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.LICENSE_ACCEPT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "LICENSE_ACCEPT" (
  "LICENSEACCEPTID" NUMBER(12,0) NOT NULL,
  "LASTNAME" VARCHAR2(50 BYTE) NULL,
  "FIRSTNAME" VARCHAR2(50 BYTE) NULL,
  "USERNAME" VARCHAR2(50 BYTE) NULL,
  "USERID" NUMBER(12,0) NULL,
  "ACCEPTDATE" DATE NULL,
  "LICENSEID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047550"
  ON "LICENSE_ACCEPT" ( 
    "LICENSEACCEPTID");
ALTER TABLE "LICENSE_ACCEPT" ADD ( 
  CONSTRAINT "SYS_C0047550" 
    PRIMARY KEY ( "LICENSEACCEPTID") 
    USING INDEX "SYS_C0047550" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.LICENSE_ACCEPT_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "LICENSE_ACCEPT_AUDIT" (
  "LICENSEACCEPTAUDITID" NUMBER(12,0) NOT NULL,
  "LASTNAME" VARCHAR2(50 BYTE) NULL,
  "FIRSTNAME" VARCHAR2(50 BYTE) NULL,
  "USERNAME" VARCHAR2(50 BYTE) NULL,
  "USERID" NUMBER(12,0) NULL,
  "ACCEPTDATE" DATE NULL,
  "LICENSEID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "LICENSEACCEPTID" NUMBER(12,0) NULL);
-- ****** Object: Table NBT.LOGMESSAGES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "LOGMESSAGES" (
  "LOGMESSAGEID" NUMBER(12,0) NOT NULL,
  "ACCESS_ID" VARCHAR2(32 BYTE) NULL,
  "APP_STATE" VARCHAR2(32 BYTE) NULL,
  "CLASS_NAME" VARCHAR2(32 BYTE) NULL,
  "CLIENT_THREAD_RUNWARN" VARCHAR2(32 BYTE) NULL,
  "CLIENT_THREAD_SHUTDOWN" VARCHAR2(32 BYTE) NULL,
  "DB_QUERY" VARCHAR2(32 BYTE) NULL,
  "DB_QUERYTIME" VARCHAR2(32 BYTE) NULL,
  "DB_RECORDCOUNT" VARCHAR2(32 BYTE) NULL,
  "ESCOTERIC_MESSAGE" VARCHAR2(32 BYTE) NULL,
  "EXOTERIC_MESSAGE" VARCHAR2(32 BYTE) NULL,
  "HTTP_ELAPSEDREQUESTSECONDS" VARCHAR2(32 BYTE) NULL,
  "HTTP_ELAPSEDSECONDS" VARCHAR2(32 BYTE) NULL,
  "HTTP_URL" VARCHAR2(32 BYTE) NULL,
  "HTTP_" VARCHAR2(32 BYTE) NULL,
  "INNER_EXCEPTION" VARCHAR2(32 BYTE) NULL,
  "MESSAGE_IDENTIFIER" VARCHAR2(32 BYTE) NULL,
  "METHOD_NAME" VARCHAR2(32 BYTE) NULL,
  "SESSION_ID" VARCHAR2(32 BYTE) NULL,
  "STACK_TRACE" VARCHAR2(32 BYTE) NULL,
  "TIME_REPORTED" VARCHAR2(32 BYTE) NULL,
  "TRACE_INFO" VARCHAR2(32 BYTE) NULL,
  "USER_NAME" VARCHAR2(32 BYTE) NULL,
  "OP_ID" VARCHAR2(32 BYTE) NULL,
  "SQL_TYPE_COUNT_INSERT" VARCHAR2(32 BYTE) NULL,
  "SQL_TYPE_COUNT_SELECT" VARCHAR2(32 BYTE) NULL,
  "SQL_TYPE_COUNT_UPDATE" VARCHAR2(32 BYTE) NULL,
  "SQL_TYPE_COUNT_DELETE" VARCHAR2(32 BYTE) NULL);
CREATE UNIQUE INDEX "SYS_C0047571"
  ON "LOGMESSAGES" ( 
    "LOGMESSAGEID");
ALTER TABLE "LOGMESSAGES" ADD ( 
  CONSTRAINT "SYS_C0047571" 
    PRIMARY KEY ( "LOGMESSAGEID") 
    USING INDEX "SYS_C0047571" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table Trigger NBT.LOGMESSAGEID_TRIG Script Date: 10/22/2012 10:27:27 AM ******
CREATE TRIGGER "NBT"."LOGMESSAGEID_TRIG" before insert on logmessages for each row begin select logmessageid_seq.nextval into :new.logmessageid from dual; end;


;
/
-- ****** Object: Table NBT.MODULES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "MODULES" (
  "DELETED" CHAR(1 BYTE) NULL,
  "DESCRIPTION" VARCHAR2(255 BYTE) NULL,
  "ENABLED" CHAR(1 BYTE) NULL,
  "MODULEID" NUMBER(12,0) NOT NULL,
  "NAME" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "MODULEID_PK"
  ON "MODULES" ( 
    "MODULEID");
ALTER TABLE "MODULES" ADD ( 
  CONSTRAINT "MODULEID_PK" 
    PRIMARY KEY ( "MODULEID") 
    USING INDEX "MODULEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODE_VIEWS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODE_VIEWS" (
  "AUDITFLAG" CHAR(1 BYTE) NULL,
  "NODEVIEWID" NUMBER(12,0) NOT NULL,
  "ROLEID" NUMBER(12,0) NULL,
  "USERID" NUMBER(12,0) NULL,
  "VIEWXML" CLOB NULL,
  "VISIBILITY" VARCHAR2(10 BYTE) NULL,
  "CATEGORY" VARCHAR2(40 BYTE) NULL,
  "FORMOBILE" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "VIEWMODE" VARCHAR2(10 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "VIEWNAME" VARCHAR2(200 BYTE) NULL)
  STORAGE ( 
    INITIAL 262144
    NEXT 1048576 ) ;
CREATE INDEX "VIEW1"
  ON "NODE_VIEWS" ( 
    "ROLEID", 
    "USERID", 
    "VISIBILITY");
CREATE UNIQUE INDEX "NODEVIEWID_PK"
  ON "NODE_VIEWS" ( 
    "NODEVIEWID");
ALTER TABLE "NODE_VIEWS" ADD ( 
  CONSTRAINT "NODEVIEWID_PK" 
    PRIMARY KEY ( "NODEVIEWID") 
    USING INDEX "NODEVIEWID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODE_VIEWS_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODE_VIEWS_AUDIT" (
  "AUDITFLAG" CHAR(1 BYTE) NULL,
  "NODEVIEWSAUDITID" NUMBER(12,0) NOT NULL,
  "ROLEID" NUMBER(12,0) NULL,
  "USERID" NUMBER(12,0) NULL,
  "VIEWNAME" VARCHAR2(30 BYTE) NULL,
  "VIEWXML" CLOB NULL,
  "VISIBILITY" VARCHAR2(10 BYTE) NULL,
  "CATEGORY" VARCHAR2(40 BYTE) NULL,
  "FORMOBILE" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "VIEWMODE" VARCHAR2(10 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "NODEVIEWID" NUMBER(12,0) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.NODES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODES" (
  "NODEID" NUMBER(12,0) NOT NULL,
  "NODENAME" VARCHAR2(100 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "PENDINGUPDATE" CHAR(1 BYTE) NULL,
  "ISSYSTEM" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "LOCKED" CHAR(1 BYTE) NULL,
  "ISTEMP" CHAR(1 BYTE) NULL,
  "SESSIONID" VARCHAR2(50 BYTE) NULL,
  "HIDDEN" CHAR(1 BYTE) NULL,
  CONSTRAINT "N_NODETYPEID_FK" 
    FOREIGN KEY ( "NODETYPEID")
       REFERENCES "NODETYPES" ( "NODETYPEID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE INDEX "NODES3"
  ON "NODES" ( 
    "NODEID", 
    "NODENAME", 
    "NODETYPEID", 
    "LOCKED", 
    "ISSYSTEM");
CREATE INDEX "NODES2"
  ON "NODES" ( 
    "NODEID", 
    "NODETYPEID");
CREATE INDEX "NODES1"
  ON "NODES" ( 
    "NODEID", 
    "NODENAME");
CREATE UNIQUE INDEX "NODEID_PK"
  ON "NODES" ( 
    "NODEID");
ALTER TABLE "NODES" ADD ( 
  CONSTRAINT "NODEID_PK" 
    PRIMARY KEY ( "NODEID") 
    USING INDEX "NODEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODES_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODES_AUDIT" (
  "NODESAUDITID" NUMBER(12,0) NOT NULL,
  "NODENAME" VARCHAR2(100 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "PENDINGUPDATE" CHAR(1 BYTE) NULL,
  "ISSYSTEM" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "NODEID" NUMBER(12,0) NULL,
  "LOCKED" CHAR(1 BYTE) NULL,
  "ISTEMP" CHAR(1 BYTE) NULL,
  "SESSIONID" VARCHAR2(50 BYTE) NULL,
  "HIDDEN" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.NODETYPE_LAYOUT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPE_LAYOUT" (
  "NODETYPELAYOUTID" NUMBER(12,0) NOT NULL,
  "LAYOUTTYPE" VARCHAR2(15 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "NODETYPEPROPID" NUMBER(12,0) NULL,
  "NODETYPETABSETID" NUMBER(12,0) NULL,
  "DISPLAY_ROW" NUMBER(12,0) NULL,
  "DISPLAY_COLUMN" NUMBER(12,0) NULL,
  "TABGROUP" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047569"
  ON "NODETYPE_LAYOUT" ( 
    "NODETYPELAYOUTID");
CREATE INDEX "IDX_01"
  ON "NODETYPE_LAYOUT" ( 
    "LAYOUTTYPE", 
    "NODETYPEPROPID");
ALTER TABLE "NODETYPE_LAYOUT" ADD ( 
  CONSTRAINT "SYS_C0047569" 
    PRIMARY KEY ( "NODETYPELAYOUTID") 
    USING INDEX "SYS_C0047569" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODETYPE_PROPS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPE_PROPS" (
  "APPEND" VARCHAR2(10 BYTE) NULL,
  "DATETODAY" CHAR(1 BYTE) NULL,
  "FIELDTYPEID" NUMBER(12,0) NULL,
  "FKVALUE" NUMBER(12,0) NULL,
  "ISBATCHENTRY" CHAR(1 BYTE) NULL,
  "ISFK" CHAR(1 BYTE) NULL,
  "ISREQUIRED" CHAR(1 BYTE) NULL,
  "ISUNIQUE" CHAR(1 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "NODETYPEPROPID" NUMBER(12,0) NOT NULL,
  "NODETYPETABSETID" NUMBER(12,0) NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NULL,
  "SERVERMANAGED" CHAR(1 BYTE) NULL,
  "TEXTAREACOLS" NUMBER(12,0) NULL,
  "TEXTAREAROWS" NUMBER(12,0) NULL,
  "TEXTLENGTH" NUMBER(12,0) NULL,
  "URL" VARCHAR2(256 BYTE) NULL,
  "VALUEPROPID" NUMBER(12,0) NULL,
  "WIDTH" NUMBER(12,0) NULL,
  "SEQUENCEID" NUMBER(12,0) NULL,
  "NUMBERPRECISION" NUMBER(12,0) NULL,
  "LISTOPTIONS" CLOB NULL,
  "COMPOSITETEMPLATE" VARCHAR2(255 BYTE) NULL,
  "FKTYPE" VARCHAR2(20 BYTE) NULL,
  "VALUEPROPTYPE" VARCHAR2(20 BYTE) NULL,
  "STATICTEXT" VARCHAR2(255 BYTE) NULL,
  "MULTI" CHAR(1 BYTE) NULL,
  "NODEVIEWID" NUMBER(12,0) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "NUMBERMINVALUE" NUMBER(15,6) NULL,
  "NUMBERMAXVALUE" NUMBER(15,6) NULL,
  "USENUMBERING" CHAR(1 BYTE) NULL,
  "QUESTIONNO" NUMBER(12,0) NULL,
  "SUBQUESTIONNO" NUMBER(12,0) NULL,
  "FILTER" CLOB NULL,
  "FILTERPROPID" NUMBER(12,0) NULL,
  "FIRSTPROPVERSIONID" NUMBER(12,0) NULL,
  "PRIORPROPVERSIONID" NUMBER(12,0) NULL,
  "VALUEOPTIONS" CLOB NULL,
  "DEFAULTVALUE" VARCHAR2(255 BYTE) NULL,
  "HELPTEXT" CLOB NULL,
  "PROPNAME" VARCHAR2(512 BYTE) NULL,
  "DEFAULTVALUEID" NUMBER(12,0) NULL,
  "ISQUICKSEARCH" CHAR(1 BYTE) NULL,
  "EXTENDED" VARCHAR2(10 BYTE) NULL,
  "HIDEINMOBILE" CHAR(1 BYTE) NULL,
  "MOBILESEARCH" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "ISCOMPOUNDUNIQUE" CHAR(1 BYTE) NULL,
  "ATTRIBUTE1" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE2" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE3" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE4" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE5" VARCHAR2(100 BYTE) NULL,
  CONSTRAINT "NTP_SEQUENCEID_FK" 
    FOREIGN KEY ( "SEQUENCEID")
       REFERENCES "SEQUENCES" ( "SEQUENCEID") 
    ENABLE 
    VALIDATE,
  CONSTRAINT "NTP_OBJECTCLASSPROPID_FK" 
    FOREIGN KEY ( "OBJECTCLASSPROPID")
       REFERENCES "OBJECT_CLASS_PROPS" ( "OBJECTCLASSPROPID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    INITIAL 131072
    NEXT 1048576 ) ;
CREATE INDEX "PROP8"
  ON "NODETYPE_PROPS" ( 
    "NODETYPEPROPID", 
    "OBJECTCLASSPROPID", 
    "NODETYPEID", 
    "FIELDTYPEID", 
    "PROPNAME");
CREATE INDEX "PROP7"
  ON "NODETYPE_PROPS" ( 
    "NODETYPEPROPID", 
    "FIRSTPROPVERSIONID", 
    "PROPNAME", 
    "NODETYPEID", 
    "FIELDTYPEID");
CREATE INDEX "PROP6"
  ON "NODETYPE_PROPS" ( 
    "NODETYPEPROPID", 
    "FIRSTPROPVERSIONID", 
    "PROPNAME", 
    "NODETYPEID");
CREATE INDEX "PROP5"
  ON "NODETYPE_PROPS" ( 
    "OBJECTCLASSPROPID");
CREATE INDEX "PROP4"
  ON "NODETYPE_PROPS" ( 
    "FIELDTYPEID");
CREATE INDEX "PROP3"
  ON "NODETYPE_PROPS" ( 
    "FIELDTYPEID", 
    "NODETYPEID", 
    "NODETYPEPROPID");
CREATE INDEX "PROP1"
  ON "NODETYPE_PROPS" ( 
    "NODETYPEID", 
    "NODETYPEPROPID");
CREATE INDEX "PROPSBYNODETYPE"
  ON "NODETYPE_PROPS" ( 
    "NODETYPEID");
CREATE UNIQUE INDEX "NODETYPEPROPID_PK"
  ON "NODETYPE_PROPS" ( 
    "NODETYPEPROPID");
ALTER TABLE "NODETYPE_PROPS" ADD ( 
  CONSTRAINT "NODETYPEPROPID_PK" 
    PRIMARY KEY ( "NODETYPEPROPID") 
    USING INDEX "NODETYPEPROPID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODETYPE_PROPS_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPE_PROPS_AUDIT" (
  "APPEND" VARCHAR2(10 BYTE) NULL,
  "DATETODAY" CHAR(1 BYTE) NULL,
  "DISPLAY_COL" NUMBER(12,0) NULL,
  "DISPLAY_ROW" NUMBER(12,0) NULL,
  "FIELDTYPEID" NUMBER(12,0) NULL,
  "FKVALUE" NUMBER(12,0) NULL,
  "ISBATCHENTRY" CHAR(1 BYTE) NULL,
  "ISFK" CHAR(1 BYTE) NULL,
  "ISREQUIRED" CHAR(1 BYTE) NULL,
  "ISUNIQUE" CHAR(1 BYTE) NULL,
  "LENGTH" NUMBER(12,0) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "NODETYPEPROPSAUDITID" NUMBER(12,0) NOT NULL,
  "NODETYPETABSETID" NUMBER(12,0) NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NULL,
  "SERVERMANAGED" CHAR(1 BYTE) NULL,
  "TEXTAREACOLS" NUMBER(12,0) NULL,
  "TEXTAREAROWS" NUMBER(12,0) NULL,
  "TEXTLENGTH" NUMBER(12,0) NULL,
  "URL" VARCHAR2(256 BYTE) NULL,
  "VALUEPROPID" NUMBER(12,0) NULL,
  "WIDTH" NUMBER(12,0) NULL,
  "SEQUENCEID" NUMBER(12,0) NULL,
  "NUMBERPRECISION" NUMBER(12,0) NULL,
  "LISTOPTIONS" CLOB NULL,
  "COMPOSITETEMPLATE" VARCHAR2(255 BYTE) NULL,
  "FKTYPE" VARCHAR2(20 BYTE) NULL,
  "VALUEPROPTYPE" VARCHAR2(20 BYTE) NULL,
  "STATICTEXT" VARCHAR2(255 BYTE) NULL,
  "MULTI" CHAR(1 BYTE) NULL,
  "NODEVIEWID" NUMBER(12,0) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "DISPLAY_COL_ADD" NUMBER(12,0) NULL,
  "DISPLAY_ROW_ADD" NUMBER(12,0) NULL,
  "SETVALONADD" CHAR(1 BYTE) NULL,
  "NUMBERMINVALUE" NUMBER(15,6) NULL,
  "NUMBERMAXVALUE" NUMBER(15,6) NULL,
  "USENUMBERING" CHAR(1 BYTE) NULL,
  "QUESTIONNO" NUMBER(12,0) NULL,
  "SUBQUESTIONNO" NUMBER(12,0) NULL,
  "FILTER" CLOB NULL,
  "FILTERPROPID" NUMBER(12,0) NULL,
  "FIRSTPROPVERSIONID" NUMBER(12,0) NULL,
  "PRIORPROPVERSIONID" NUMBER(12,0) NULL,
  "VALUEOPTIONS" CLOB NULL,
  "DEFAULTVALUE" VARCHAR2(255 BYTE) NULL,
  "HELPTEXT" CLOB NULL,
  "PROPNAME" VARCHAR2(512 BYTE) NULL,
  "DEFAULTVALUEID" NUMBER(12,0) NULL,
  "ISQUICKSEARCH" CHAR(1 BYTE) NULL,
  "EXTENDED" VARCHAR2(10 BYTE) NULL,
  "HIDEINMOBILE" CHAR(1 BYTE) NULL,
  "MOBILESEARCH" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "NODETYPEPROPID" NUMBER(12,0) NULL,
  "ISCOMPOUNDUNIQUE" CHAR(1 BYTE) NULL,
  "ATTRIBUTE1" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE2" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE3" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE4" VARCHAR2(100 BYTE) NULL,
  "ATTRIBUTE5" VARCHAR2(100 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.NODETYPE_TABSET Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPE_TABSET" (
  "AUDITFLAG" CHAR(1 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "NODETYPETABSETID" NUMBER(12,0) NOT NULL,
  "TABCLASS" VARCHAR2(20 BYTE) NULL,
  "TABNAME" VARCHAR2(80 BYTE) NULL,
  "TABORDER" NUMBER(12,0) NULL,
  "INCLUDEINNODEREPORT" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "FIRSTTABVERSIONID" NUMBER(12,0) NULL,
  "PRIORTABVERSIONID" NUMBER(12,0) NULL,
  "SERVERMANAGED" CHAR(1 BYTE) NULL,
  CONSTRAINT "NTTS_NODETYPEID_FK" 
    FOREIGN KEY ( "NODETYPEID")
       REFERENCES "NODETYPES" ( "NODETYPEID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "NODETYPETABSETID_PK"
  ON "NODETYPE_TABSET" ( 
    "NODETYPETABSETID");
ALTER TABLE "NODETYPE_TABSET" ADD ( 
  CONSTRAINT "NODETYPETABSETID_PK" 
    PRIMARY KEY ( "NODETYPETABSETID") 
    USING INDEX "NODETYPETABSETID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODETYPE_TABSET_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPE_TABSET_AUDIT" (
  "AUDITFLAG" CHAR(1 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "NODETYPETABSETAUDITID" NUMBER(12,0) NOT NULL,
  "TABCLASS" VARCHAR2(20 BYTE) NULL,
  "TABNAME" VARCHAR2(80 BYTE) NULL,
  "TABORDER" NUMBER(12,0) NULL,
  "INCLUDEINNODEREPORT" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "NODETYPETABSETID" NUMBER(12,0) NULL,
  "FIRSTTABVERSIONID" NUMBER(12,0) NULL,
  "PRIORTABVERSIONID" NUMBER(12,0) NULL,
  "SERVERMANAGED" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.NODETYPES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPES" (
  "ICONFILENAME" VARCHAR2(50 BYTE) NULL,
  "NAMETEMPLATE" VARCHAR2(100 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NOT NULL,
  "NODETYPENAME" VARCHAR2(50 BYTE) NULL,
  "OBJECTCLASSID" NUMBER(12,0) NULL,
  "RESTRICTCHILDREN" CHAR(1 BYTE) NULL,
  "TAB_DOCS" CHAR(1 BYTE) NULL,
  "TAB_GEO_DETAIL" CHAR(1 BYTE) NULL,
  "CATEGORY" VARCHAR2(40 BYTE) NULL,
  "ISLOCKED" CHAR(1 BYTE) NULL,
  "PRIORVERSIONID" NUMBER(12,0) NULL,
  "VERSIONNO" NUMBER(12,0) NULL,
  "FIRSTVERSIONID" NUMBER(12,0) NULL,
  "TABLENAME" VARCHAR2(40 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "QUOTA" NUMBER(12,0) NULL,
  "ENABLED" CHAR(1 BYTE) NULL,
  "HASLABEL" CHAR(1 BYTE) NULL,
  CONSTRAINT "NT_OBJECTCLASSID_FK" 
    FOREIGN KEY ( "OBJECTCLASSID")
       REFERENCES "OBJECT_CLASS" ( "OBJECTCLASSID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "NODETYPEID_PK"
  ON "NODETYPES" ( 
    "NODETYPEID");
ALTER TABLE "NODETYPES" ADD ( 
  CONSTRAINT "NODETYPEID_PK" 
    PRIMARY KEY ( "NODETYPEID") 
    USING INDEX "NODETYPEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.NODETYPES_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "NODETYPES_AUDIT" (
  "ICONFILENAME" VARCHAR2(50 BYTE) NULL,
  "NAMETEMPLATE" VARCHAR2(100 BYTE) NULL,
  "NODETYPESAUDITID" NUMBER(12,0) NOT NULL,
  "NODETYPENAME" VARCHAR2(50 BYTE) NULL,
  "OBJECTCLASSID" NUMBER(12,0) NULL,
  "RESTRICTCHILDREN" CHAR(1 BYTE) NULL,
  "TAB_DOCS" CHAR(1 BYTE) NULL,
  "TAB_GEO_DETAIL" CHAR(1 BYTE) NULL,
  "CATEGORY" VARCHAR2(40 BYTE) NULL,
  "ISLOCKED" CHAR(1 BYTE) NULL,
  "PRIORVERSIONID" NUMBER(12,0) NULL,
  "VERSIONNO" NUMBER(12,0) NULL,
  "FIRSTVERSIONID" NUMBER(12,0) NULL,
  "TABLENAME" VARCHAR2(40 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "QUOTA" NUMBER(12,0) NULL,
  "ENABLED" CHAR(1 BYTE) NULL,
  "HASLABEL" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.OBJECT_CLASS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "OBJECT_CLASS" (
  "OBJECTCLASS" VARCHAR2(50 BYTE) NULL,
  "OBJECTCLASSID" NUMBER(12,0) NOT NULL,
  "USE_BATCH_ENTRY" CHAR(1 BYTE) NULL,
  "ICONFILENAME" VARCHAR2(50 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "QUOTA" NUMBER(12,0) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "OBJECTCLASSID_PK"
  ON "OBJECT_CLASS" ( 
    "OBJECTCLASSID");
ALTER TABLE "OBJECT_CLASS" ADD ( 
  CONSTRAINT "OBJECTCLASSID_PK" 
    PRIMARY KEY ( "OBJECTCLASSID") 
    USING INDEX "OBJECTCLASSID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.OBJECT_CLASS_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "OBJECT_CLASS_AUDIT" (
  "OBJECTCLASS" VARCHAR2(50 BYTE) NULL,
  "OBJECTCLASSAUDITID" NUMBER(12,0) NOT NULL,
  "USE_BATCH_ENTRY" CHAR(1 BYTE) NULL,
  "ICONFILENAME" VARCHAR2(50 BYTE) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "OBJECTCLASSID" NUMBER(12,0) NULL,
  "QUOTA" NUMBER(12,0) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.OBJECT_CLASS_PROPS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "OBJECT_CLASS_PROPS" (
  "FIELDTYPEID" NUMBER(12,0) NULL,
  "FKVALUE" NUMBER(12,0) NULL,
  "ISBATCHENTRY" CHAR(1 BYTE) NULL,
  "ISFK" CHAR(1 BYTE) NULL,
  "ISREQUIRED" CHAR(1 BYTE) NULL,
  "ISUNIQUE" CHAR(1 BYTE) NULL,
  "OBJECTCLASSID" NUMBER(12,0) NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NOT NULL,
  "SERVERMANAGED" CHAR(1 BYTE) NULL,
  "VALUEFIELDID" NUMBER(12,0) NULL,
  "NUMBERPRECISION" NUMBER(12,0) NULL,
  "LISTOPTIONS" CLOB NULL,
  "VIEWXML" CLOB NULL,
  "FKTYPE" VARCHAR2(20 BYTE) NULL,
  "MULTI" CHAR(1 BYTE) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "DISPLAY_COL_ADD" NUMBER(12,0) NULL,
  "DISPLAY_ROW_ADD" NUMBER(12,0) NULL,
  "SETVALONADD" CHAR(1 BYTE) NULL,
  "NUMBERMINVALUE" NUMBER(15,6) NULL,
  "NUMBERMAXVALUE" NUMBER(15,6) NULL,
  "STATICTEXT" VARCHAR2(255 BYTE) NULL,
  "FILTER" CLOB NULL,
  "FILTERPROPID" NUMBER(12,0) NULL,
  "VALUEOPTIONS" CLOB NULL,
  "PROPNAME" VARCHAR2(512 BYTE) NULL,
  "ISGLOBALUNIQUE" CHAR(1 BYTE) NULL,
  "EXTENDED" VARCHAR2(10 BYTE) NULL,
  "DEFAULTVALUEID" NUMBER(12,0) NULL,
  "AUDITLEVEL" VARCHAR2(10 BYTE) NULL,
  "USENUMBERING" CHAR(1 BYTE) NULL,
  "ISCOMPOUNDUNIQUE" CHAR(1 BYTE) NULL,
  "VALUEPROPID" NUMBER(12,0) NULL,
  "VALUEPROPTYPE" VARCHAR2(40 BYTE) NULL,
  "TEXTAREAROWS" NUMBER(12,0) NULL,
  "TEXTAREACOLS" NUMBER(12,0) NULL,
  CONSTRAINT "OCP_OBJECTCLASSID_FK" 
    FOREIGN KEY ( "OBJECTCLASSID")
       REFERENCES "OBJECT_CLASS" ( "OBJECTCLASSID") 
    ENABLE 
    VALIDATE,
  CONSTRAINT "OCP_FIELDTYPEID_FK" 
    FOREIGN KEY ( "FIELDTYPEID")
       REFERENCES "FIELD_TYPES" ( "FIELDTYPEID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "OBJECTCLASSPROPID_PK"
  ON "OBJECT_CLASS_PROPS" ( 
    "OBJECTCLASSPROPID");
ALTER TABLE "OBJECT_CLASS_PROPS" ADD ( 
  CONSTRAINT "OBJECTCLASSPROPID_PK" 
    PRIMARY KEY ( "OBJECTCLASSPROPID") 
    USING INDEX "OBJECTCLASSPROPID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.OBJECT_CLASS_PROPS_AUDIT Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "OBJECT_CLASS_PROPS_AUDIT" (
  "FIELDTYPEID" NUMBER(12,0) NULL,
  "FKVALUE" NUMBER(12,0) NULL,
  "ISBATCHENTRY" CHAR(1 BYTE) NULL,
  "ISFK" CHAR(1 BYTE) NULL,
  "ISREQUIRED" CHAR(1 BYTE) NULL,
  "ISUNIQUE" CHAR(1 BYTE) NULL,
  "OBJECTCLASSID" NUMBER(12,0) NULL,
  "OBJECTCLASSPROPSAUDITID" NUMBER(12,0) NOT NULL,
  "SERVERMANAGED" CHAR(1 BYTE) NULL,
  "VALUEFIELDID" NUMBER(12,0) NULL,
  "NUMBERPRECISION" NUMBER(12,0) NULL,
  "LISTOPTIONS" CLOB NULL,
  "VIEWXML" CLOB NULL,
  "FKTYPE" VARCHAR2(20 BYTE) NULL,
  "MULTI" CHAR(1 BYTE) NULL,
  "READONLY" CHAR(1 BYTE) NULL,
  "DISPLAY_COL_ADD" NUMBER(12,0) NULL,
  "DISPLAY_ROW_ADD" NUMBER(12,0) NULL,
  "SETVALONADD" CHAR(1 BYTE) NULL,
  "NUMBERMINVALUE" NUMBER(15,6) NULL,
  "NUMBERMAXVALUE" NUMBER(15,6) NULL,
  "STATICTEXT" VARCHAR2(255 BYTE) NULL,
  "FILTER" CLOB NULL,
  "FILTERPROPID" NUMBER(12,0) NULL,
  "VALUEOPTIONS" CLOB NULL,
  "PROPNAME" VARCHAR2(512 BYTE) NULL,
  "ISGLOBALUNIQUE" CHAR(1 BYTE) NULL,
  "EXTENDED" VARCHAR2(10 BYTE) NULL,
  "DEFAULTVALUEID" NUMBER(12,0) NULL,
  "AUDITEVENTTYPE" VARCHAR2(14 BYTE) NULL,
  "AUDITTRANSACTIONID" NUMBER(12,0) NULL,
  "RECORDCREATED" DATE NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NULL,
  "VALUEPROPID" VARCHAR2(20 BYTE) NULL,
  "VALUEPROPTYPE" NUMBER(15,6) NULL,
  "USENUMBERING" CHAR(1 BYTE) NULL,
  "ISCOMPOUNDUNIQUE" CHAR(1 BYTE) NULL,
  "TEXTAREAROWS" NUMBER(12,0) NULL,
  "TEXTAREACOLS" NUMBER(12,0) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
-- ****** Object: Table NBT.SCHEDULEDRULEPARAMS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "SCHEDULEDRULEPARAMS" (
  "SCHEDULEDRULEPARAMID" NUMBER(12,0) NOT NULL,
  "SCHEDULEDRULEID" NUMBER(12,0) NULL,
  "PARAMNAME" VARCHAR2(50 BYTE) NULL,
  "PARAMVAL" VARCHAR2(250 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047567"
  ON "SCHEDULEDRULEPARAMS" ( 
    "SCHEDULEDRULEPARAMID");
ALTER TABLE "SCHEDULEDRULEPARAMS" ADD ( 
  CONSTRAINT "SYS_C0047567" 
    PRIMARY KEY ( "SCHEDULEDRULEPARAMID") 
    USING INDEX "SYS_C0047567" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.SCHEDULEDRULES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "SCHEDULEDRULES" (
  "SCHEDULEDRULEID" NUMBER(12,0) NOT NULL,
  "RULENAME" VARCHAR2(50 BYTE) NULL,
  "MAXRUNTIMEMS" NUMBER(12,0) NULL,
  "THREADID" NUMBER(12,0) NULL,
  "REPROBATETHRESHOLD" NUMBER(12,0) NULL,
  "TOTALROGUECOUNT" NUMBER(12,0) NULL,
  "FAILEDCOUNT" NUMBER(12,0) NULL,
  "REPROBATE" CHAR(1 BYTE) NULL,
  "DISABLED" CHAR(1 BYTE) NULL,
  "STATUSMESSAGE" VARCHAR2(512 BYTE) NULL,
  "RECURRENCE" VARCHAR2(512 BYTE) NULL,
  "INTERVAL" NUMBER(12,0) NULL,
  "RUNSTARTTIME" DATE NULL,
  "RUNENDTIME" DATE NULL,
  "LASTRUN" DATE NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047566"
  ON "SCHEDULEDRULES" ( 
    "SCHEDULEDRULEID");
ALTER TABLE "SCHEDULEDRULES" ADD ( 
  CONSTRAINT "SYS_C0047566" 
    PRIMARY KEY ( "SCHEDULEDRULEID") 
    USING INDEX "SYS_C0047566" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.SEQUENCES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "SEQUENCES" (
  "SEQUENCEID" NUMBER(12,0) NOT NULL,
  "SEQUENCENAME" VARCHAR2(25 BYTE) NULL,
  "PREP" VARCHAR2(25 BYTE) NULL,
  "POST" VARCHAR2(25 BYTE) NULL,
  "PAD" NUMBER(12,0) NULL,
  "AUDITFLAG" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SEQUENCEID_PK"
  ON "SEQUENCES" ( 
    "SEQUENCEID");
ALTER TABLE "SEQUENCES" ADD ( 
  CONSTRAINT "SEQUENCEID_PK" 
    PRIMARY KEY ( "SEQUENCEID") 
    USING INDEX "SEQUENCEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.SESSION_DATA Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "SESSION_DATA" (
  "SESSIONDATAID" NUMBER(12,0) NOT NULL,
  "SESSIONID" VARCHAR2(50 BYTE) NULL,
  "SESSIONDATATYPE" VARCHAR2(10 BYTE) NULL,
  "ACTIONID" NUMBER(12,0) NULL,
  "VIEWID" NUMBER(12,0) NULL,
  "VIEWMODE" VARCHAR2(10 BYTE) NULL,
  "VIEWXML" CLOB NULL,
  "QUICKLAUNCH" CHAR(1 BYTE) NULL,
  "KEEPINQUICKLAUNCH" CHAR(1 BYTE) NULL,
  "NAME" VARCHAR2(1000 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047580"
  ON "SESSION_DATA" ( 
    "SESSIONDATAID");
ALTER TABLE "SESSION_DATA" ADD ( 
  CONSTRAINT "SYS_C0047580" 
    PRIMARY KEY ( "SESSIONDATAID") 
    USING INDEX "SYS_C0047580" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.SESSIONLIST Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "SESSIONLIST" (
  "SESSIONLISTID" NUMBER(12,0) NOT NULL,
  "SESSIONID" VARCHAR2(50 BYTE) NULL,
  "ACCESSID" VARCHAR2(50 BYTE) NULL,
  "USERID" VARCHAR2(50 BYTE) NULL,
  "USERNAME" VARCHAR2(50 BYTE) NULL,
  "IPADDRESS" VARCHAR2(50 BYTE) NULL,
  "CSWPRIMEKEY" VARCHAR2(50 BYTE) NULL,
  "ROLETIMEOUTMINUTES" NUMBER(15,6) NULL,
  "TIMEOUTDATE" DATE NULL,
  "LOGINDATE" DATE NULL,
  "ISMOBILE" CHAR(1 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  "ORIGINALUSERID" VARCHAR2(50 BYTE) NULL,
  "ORIGINALUSERNAME" VARCHAR2(50 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047557"
  ON "SESSIONLIST" ( 
    "SESSIONLISTID");
CREATE UNIQUE INDEX "SESSIONLIST_SESSIONID"
  ON "SESSIONLIST" ( 
    "SESSIONID");
ALTER TABLE "SESSIONLIST" ADD ( 
  CONSTRAINT "SYS_C0047557" 
    PRIMARY KEY ( "SESSIONLISTID") 
    USING INDEX "SYS_C0047557" 
    ENABLE 
    VALIDATE );
ALTER TABLE "SESSIONLIST" ADD ( 
  CONSTRAINT "SESSIONLIST_SESSIONID" 
    UNIQUE ( "SESSIONID") 
    USING INDEX "SESSIONLIST_SESSIONID" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATIC_SQL_SELECTS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATIC_SQL_SELECTS" (
  "DATADICTIONARYID" NUMBER(12,0) NULL,
  "DD_COLUMNNAME" VARCHAR2(50 BYTE) NULL,
  "DD_TABLENAME" VARCHAR2(50 BYTE) NULL,
  "DELETED" CHAR(1 BYTE) NULL,
  "QUERYID" VARCHAR2(80 BYTE) NULL,
  "QUERYTEXT" CLOB NULL,
  "STATICSQLSELECTID" NUMBER(12,0) NOT NULL,
  CONSTRAINT "S4_DATADICTIONARYID_FK" 
    FOREIGN KEY ( "DATADICTIONARYID")
       REFERENCES "DATA_DICTIONARY" ( "TABLECOLID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATICSQLSELECTID_PK"
  ON "STATIC_SQL_SELECTS" ( 
    "STATICSQLSELECTID");
ALTER TABLE "STATIC_SQL_SELECTS" ADD ( 
  CONSTRAINT "STATICSQLSELECTID_PK" 
    PRIMARY KEY ( "STATICSQLSELECTID") 
    USING INDEX "STATICSQLSELECTID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATISTICS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATISTICS" (
  "STATISTICSID" NUMBER(12,0) NOT NULL,
  "USERID" NUMBER(12,0) NULL,
  "LOGINDATE" DATE NULL,
  "LOGOUTDATE" DATE NULL,
  "COUNT_LIFECYCLES" NUMBER(12,0) NULL,
  "COUNT_MULTIEDIT" NUMBER(12,0) NULL,
  "COUNT_REPORTRUNS" NUMBER(12,0) NULL,
  "COUNT_VIEWLOADS" NUMBER(12,0) NULL,
  "COUNT_NODESSAVED" NUMBER(12,0) NULL,
  "COUNT_NODESADDED" NUMBER(12,0) NULL,
  "COUNT_NODESCOPIED" NUMBER(12,0) NULL,
  "COUNT_NODESDELETED" NUMBER(12,0) NULL,
  "COUNT_VIEWSEDITED" NUMBER(12,0) NULL,
  "USERLOGGEDOUT" CHAR(1 BYTE) NULL,
  "AVERAGE_SERVERTIME" NUMBER(15,6) NULL,
  "USERNAME" VARCHAR2(100 BYTE) NULL,
  "COUNT_ACTIONLOADS" NUMBER(12,0) NULL,
  "COUNT_ERRORS" NUMBER(12,0) NULL,
  "COUNT_SEARCHES" NUMBER(12,0) NULL,
  "COUNT_VIEWFILTERMODS" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATISTICSID_PK"
  ON "STATISTICS" ( 
    "STATISTICSID");
ALTER TABLE "STATISTICS" ADD ( 
  CONSTRAINT "STATISTICSID_PK" 
    PRIMARY KEY ( "STATISTICSID") 
    USING INDEX "STATISTICSID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATISTICS_ACTIONS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATISTICS_ACTIONS" (
  "STATISTICSACTIONID" NUMBER(12,0) NOT NULL,
  "STATISTICSID" NUMBER(12,0) NULL,
  "ACTIONNAME" VARCHAR2(50 BYTE) NULL,
  "HITCOUNT" NUMBER(12,0) NULL,
  "ACTION" VARCHAR2(20 BYTE) NULL,
  "ACTIONID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  CONSTRAINT "SA_STATISTICSID_FK" 
    FOREIGN KEY ( "STATISTICSID")
       REFERENCES "STATISTICS" ( "STATISTICSID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATISTICSACTIONID_PK"
  ON "STATISTICS_ACTIONS" ( 
    "STATISTICSACTIONID");
ALTER TABLE "STATISTICS_ACTIONS" ADD ( 
  CONSTRAINT "STATISTICSACTIONID_PK" 
    PRIMARY KEY ( "STATISTICSACTIONID") 
    USING INDEX "STATISTICSACTIONID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATISTICS_NODETYPES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATISTICS_NODETYPES" (
  "STATISTICSNODETYPEID" NUMBER(12,0) NOT NULL,
  "STATISTICSID" NUMBER(12,0) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "HITCOUNT" NUMBER(12,0) NULL,
  "ACTION" VARCHAR2(20 BYTE) NULL,
  "NODETYPENAME" VARCHAR2(50 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  CONSTRAINT "SO_STATISTICSID_FK" 
    FOREIGN KEY ( "STATISTICSID")
       REFERENCES "STATISTICS" ( "STATISTICSID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATISTICSNODETYPEID_PK"
  ON "STATISTICS_NODETYPES" ( 
    "STATISTICSNODETYPEID");
ALTER TABLE "STATISTICS_NODETYPES" ADD ( 
  CONSTRAINT "STATISTICSNODETYPEID_PK" 
    PRIMARY KEY ( "STATISTICSNODETYPEID") 
    USING INDEX "STATISTICSNODETYPEID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATISTICS_REPORTS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATISTICS_REPORTS" (
  "STATISTICSREPORTID" NUMBER(12,0) NOT NULL,
  "STATISTICSID" NUMBER(12,0) NULL,
  "REPORTID" NUMBER(12,0) NULL,
  "HITCOUNT" NUMBER(12,0) NULL,
  "ACTION" VARCHAR2(20 BYTE) NULL,
  "REPORTNAME" VARCHAR2(100 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  CONSTRAINT "SR_STATISTICSID_FK" 
    FOREIGN KEY ( "STATISTICSID")
       REFERENCES "STATISTICS" ( "STATISTICSID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATISTICSREPORTID_PK"
  ON "STATISTICS_REPORTS" ( 
    "STATISTICSREPORTID");
ALTER TABLE "STATISTICS_REPORTS" ADD ( 
  CONSTRAINT "STATISTICSREPORTID_PK" 
    PRIMARY KEY ( "STATISTICSREPORTID") 
    USING INDEX "STATISTICSREPORTID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATISTICS_SEARCHES Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATISTICS_SEARCHES" (
  "STATISTICSSEARCHID" NUMBER(12,0) NOT NULL,
  "STATISTICSID" NUMBER(12,0) NULL,
  "NODETYPEPROPID" NUMBER(12,0) NULL,
  "OBJECTCLASSPROPID" NUMBER(12,0) NULL,
  "PROPNAME" VARCHAR2(50 BYTE) NULL,
  "HITCOUNT" NUMBER(12,0) NULL,
  "ACTION" VARCHAR2(20 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  CONSTRAINT "SS_STATISTICSID_FK" 
    FOREIGN KEY ( "STATISTICSID")
       REFERENCES "STATISTICS" ( "STATISTICSID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATISTICSSEARCHID_PK"
  ON "STATISTICS_SEARCHES" ( 
    "STATISTICSSEARCHID");
ALTER TABLE "STATISTICS_SEARCHES" ADD ( 
  CONSTRAINT "STATISTICSSEARCHID_PK" 
    PRIMARY KEY ( "STATISTICSSEARCHID") 
    USING INDEX "STATISTICSSEARCHID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.STATISTICS_VIEWS Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "STATISTICS_VIEWS" (
  "STATISTICSVIEWID" NUMBER(12,0) NOT NULL,
  "STATISTICSID" NUMBER(12,0) NULL,
  "NODEVIEWID" NUMBER(12,0) NULL,
  "HITCOUNT" NUMBER(12,0) NULL,
  "ACTION" VARCHAR2(20 BYTE) NULL,
  "VIEWNAME" VARCHAR2(30 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL,
  CONSTRAINT "SV_STATISTICSID_FK" 
    FOREIGN KEY ( "STATISTICSID")
       REFERENCES "STATISTICS" ( "STATISTICSID") 
    ENABLE 
    VALIDATE)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "STATISTICSVIEWID_PK"
  ON "STATISTICS_VIEWS" ( 
    "STATISTICSVIEWID");
ALTER TABLE "STATISTICS_VIEWS" ADD ( 
  CONSTRAINT "STATISTICSVIEWID_PK" 
    PRIMARY KEY ( "STATISTICSVIEWID") 
    USING INDEX "STATISTICSVIEWID_PK" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.UPDATE_HISTORY Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "UPDATE_HISTORY" (
  "UPDATEHISTORYID" NUMBER(12,0) NOT NULL,
  "UPDATEDATE" DATE NULL,
  "LOG" CLOB NULL,
  "VERSION" VARCHAR2(6 BYTE) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047579"
  ON "UPDATE_HISTORY" ( 
    "UPDATEHISTORYID");
ALTER TABLE "UPDATE_HISTORY" ADD ( 
  CONSTRAINT "SYS_C0047579" 
    PRIMARY KEY ( "UPDATEHISTORYID") 
    USING INDEX "SYS_C0047579" 
    ENABLE 
    VALIDATE );
-- ****** Object: Table NBT.WELCOME Script Date: 10/22/2012 10:27:27 AM ******
CREATE TABLE "WELCOME" (
  "WELCOMEID" NUMBER(12,0) NOT NULL,
  "ROLEID" NUMBER(12,0) NULL,
  "COMPONENTTYPE" VARCHAR2(30 BYTE) NULL,
  "DISPLAY_ROW" NUMBER(12,0) NULL,
  "DISPLAY_COL" NUMBER(12,0) NULL,
  "NODEVIEWID" NUMBER(12,0) NULL,
  "DISPLAYTEXT" VARCHAR2(255 BYTE) NULL,
  "NODETYPEID" NUMBER(12,0) NULL,
  "BUTTONICON" VARCHAR2(255 BYTE) NULL,
  "ACTIONID" NUMBER(12,0) NULL,
  "REPORTID" NUMBER(12,0) NULL,
  "ISDEMO" CHAR(1 BYTE) NULL)
  STORAGE ( 
    NEXT 1048576 ) ;
CREATE UNIQUE INDEX "SYS_C0047565"
  ON "WELCOME" ( 
    "WELCOMEID");
ALTER TABLE "WELCOME" ADD ( 
  CONSTRAINT "SYS_C0047565" 
    PRIMARY KEY ( "WELCOMEID") 
    USING INDEX "SYS_C0047565" 
    ENABLE 
    VALIDATE );
