//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSW.Nbt.WebPages {
    
    
    public partial class Act_FutureScheduling {
        
        /// <summary>
        /// FutureSchedulingWizard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizard FutureSchedulingWizard;
        
        /// <summary>
        /// FutureSchedulingWizard_Step_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizardStep FutureSchedulingWizard_Step_1;
        
        /// <summary>
        /// StepOnePlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder StepOnePlaceHolder;
        
        /// <summary>
        /// FutureSchedulingWizard_Step_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizardStep FutureSchedulingWizard_Step_2;
        
        /// <summary>
        /// StepTwoPlaceHolder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder StepTwoPlaceHolder;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ChemSW.Nbt.WebPages.MainLayout Master {
            get {
                return ((ChemSW.Nbt.WebPages.MainLayout)(base.Master));
            }
        }
    }
}
