//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSW.Nbt.WebPages {
    
    
    public partial class Act_AssignTests {
        
        /// <summary>
        /// AssignTestsWizard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizard AssignTestsWizard;
        
        /// <summary>
        /// AssignTestsWizard_Step1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizardStep AssignTestsWizard_Step1;
        
        /// <summary>
        /// Step1PH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder Step1PH;
        
        /// <summary>
        /// AssignTestsWizard_Step2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizardStep AssignTestsWizard_Step2;
        
        /// <summary>
        /// Step2PH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder Step2PH;
        
        /// <summary>
        /// AssignTestsWizard_Step3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizardStep AssignTestsWizard_Step3;
        
        /// <summary>
        /// Step3PH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder Step3PH;
        
        /// <summary>
        /// AssignTestsWizard_Step4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ChemSW.CswWebControls.CswWizardStep AssignTestsWizard_Step4;
        
        /// <summary>
        /// Step4PH control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder Step4PH;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new ChemSW.Nbt.WebPages.MainLayout Master {
            get {
                return ((ChemSW.Nbt.WebPages.MainLayout)(base.Master));
            }
        }
    }
}
