//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSW.Nbt.ChemWatchDocumentServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRequest", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.DocumentRequest))]
    public partial class ListRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SortTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string SortField {
            get {
                return this.SortFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SortFieldField, value) != true)) {
                    this.SortFieldField = value;
                    this.RaisePropertyChanged("SortField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int SortType {
            get {
                return this.SortTypeField;
            }
            set {
                if ((this.SortTypeField.Equals(value) != true)) {
                    this.SortTypeField = value;
                    this.RaisePropertyChanged("SortType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentRequest", Namespace="")]
    [System.SerializableAttribute()]
    public partial class DocumentRequest : ChemSW.Nbt.ChemWatchDocumentServices.ListRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLatestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HideGoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowOnlyGoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MSDSFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsShowOwnField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialIdField, value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Gid {
            get {
                return this.GidField;
            }
            set {
                if ((object.ReferenceEquals(this.GidField, value) != true)) {
                    this.GidField = value;
                    this.RaisePropertyChanged("Gid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int[] LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int[] CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool IsLatest {
            get {
                return this.IsLatestField;
            }
            set {
                if ((this.IsLatestField.Equals(value) != true)) {
                    this.IsLatestField = value;
                    this.RaisePropertyChanged("IsLatest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool IsPartNumber {
            get {
                return this.IsPartNumberField;
            }
            set {
                if ((this.IsPartNumberField.Equals(value) != true)) {
                    this.IsPartNumberField = value;
                    this.RaisePropertyChanged("IsPartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool HideGold {
            get {
                return this.HideGoldField;
            }
            set {
                if ((this.HideGoldField.Equals(value) != true)) {
                    this.HideGoldField = value;
                    this.RaisePropertyChanged("HideGold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool ShowOnlyGold {
            get {
                return this.ShowOnlyGoldField;
            }
            set {
                if ((this.ShowOnlyGoldField.Equals(value) != true)) {
                    this.ShowOnlyGoldField = value;
                    this.RaisePropertyChanged("ShowOnlyGold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string SourceType {
            get {
                return this.SourceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTypeField, value) != true)) {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string FolderId {
            get {
                return this.FolderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderIdField, value) != true)) {
                    this.FolderIdField = value;
                    this.RaisePropertyChanged("FolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MSDSFormat {
            get {
                return this.MSDSFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.MSDSFormatField, value) != true)) {
                    this.MSDSFormatField = value;
                    this.RaisePropertyChanged("MSDSFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool IsShowOwn {
            get {
                return this.IsShowOwnField;
            }
            set {
                if ((this.IsShowOwnField.Equals(value) != true)) {
                    this.IsShowOwnField = value;
                    this.RaisePropertyChanged("IsShowOwn");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListResultOfDocument", Namespace="")]
    [System.SerializableAttribute()]
    public partial class ListResultOfDocument : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChemSW.Nbt.ChemWatchDocumentServices.Document[] RowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExact {
            get {
                return this.IsExactField;
            }
            set {
                if ((this.IsExactField.Equals(value) != true)) {
                    this.IsExactField = value;
                    this.RaisePropertyChanged("IsExact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount {
            get {
                return this.RowCountField;
            }
            set {
                if ((this.RowCountField.Equals(value) != true)) {
                    this.RowCountField = value;
                    this.RaisePropertyChanged("RowCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChemSW.Nbt.ChemWatchDocumentServices.Document[] Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((object.ReferenceEquals(this.RowsField, value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="")]
    [System.SerializableAttribute()]
    public partial class Document : ChemSW.Nbt.ChemWatchDocumentServices.BaseNamedEntityOfstring {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LanguageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CWNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCWGoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsWeWriteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPrivateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChemwatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLatestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialIdField, value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupIdField, value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CountryId {
            get {
                return this.CountryIdField;
            }
            set {
                if ((this.CountryIdField.Equals(value) != true)) {
                    this.CountryIdField = value;
                    this.RaisePropertyChanged("CountryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string LanguageCode {
            get {
                return this.LanguageCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageCodeField, value) != true)) {
                    this.LanguageCodeField = value;
                    this.RaisePropertyChanged("LanguageCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int LanguageId {
            get {
                return this.LanguageIdField;
            }
            set {
                if ((this.LanguageIdField.Equals(value) != true)) {
                    this.LanguageIdField = value;
                    this.RaisePropertyChanged("LanguageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string SourceType {
            get {
                return this.SourceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTypeField, value) != true)) {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string CWNumber {
            get {
                return this.CWNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CWNumberField, value) != true)) {
                    this.CWNumberField = value;
                    this.RaisePropertyChanged("CWNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool IsCWGold {
            get {
                return this.IsCWGoldField;
            }
            set {
                if ((this.IsCWGoldField.Equals(value) != true)) {
                    this.IsCWGoldField = value;
                    this.RaisePropertyChanged("IsCWGold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool IsWeWrite {
            get {
                return this.IsWeWriteField;
            }
            set {
                if ((this.IsWeWriteField.Equals(value) != true)) {
                    this.IsWeWriteField = value;
                    this.RaisePropertyChanged("IsWeWrite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool IsPrivate {
            get {
                return this.IsPrivateField;
            }
            set {
                if ((this.IsPrivateField.Equals(value) != true)) {
                    this.IsPrivateField = value;
                    this.RaisePropertyChanged("IsPrivate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool IsChemwatch {
            get {
                return this.IsChemwatchField;
            }
            set {
                if ((this.IsChemwatchField.Equals(value) != true)) {
                    this.IsChemwatchField = value;
                    this.RaisePropertyChanged("IsChemwatch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool IsLatest {
            get {
                return this.IsLatestField;
            }
            set {
                if ((this.IsLatestField.Equals(value) != true)) {
                    this.IsLatestField = value;
                    this.RaisePropertyChanged("IsLatest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public string ExternalUrl {
            get {
                return this.ExternalUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalUrlField, value) != true)) {
                    this.ExternalUrlField = value;
                    this.RaisePropertyChanged("ExternalUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public string DocNo {
            get {
                return this.DocNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocNoField, value) != true)) {
                    this.DocNoField = value;
                    this.RaisePropertyChanged("DocNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOfstring", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.BaseNamedEntityOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.Document))]
    public partial class BaseEntityOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseNamedEntityOfstring", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.Document))]
    public partial class BaseNamedEntityOfstring : ChemSW.Nbt.ChemWatchDocumentServices.BaseEntityOfstring {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentLightWithMaterialAndVendor", Namespace="")]
    [System.SerializableAttribute()]
    public partial class DocumentLightWithMaterialAndVendor : ChemSW.Nbt.ChemWatchDocumentServices.BaseNamedEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MaterialIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long VendorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MaterialId {
            get {
                return this.MaterialIdField;
            }
            set {
                if ((this.MaterialIdField.Equals(value) != true)) {
                    this.MaterialIdField = value;
                    this.RaisePropertyChanged("MaterialId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaterialName {
            get {
                return this.MaterialNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialNameField, value) != true)) {
                    this.MaterialNameField = value;
                    this.RaisePropertyChanged("MaterialName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long VendorId {
            get {
                return this.VendorIdField;
            }
            set {
                if ((this.VendorIdField.Equals(value) != true)) {
                    this.VendorIdField = value;
                    this.RaisePropertyChanged("VendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VendorName {
            get {
                return this.VendorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorNameField, value) != true)) {
                    this.VendorNameField = value;
                    this.RaisePropertyChanged("VendorName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntityOflong", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.BaseNamedEntityOflong))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.DocumentLightWithMaterialAndVendor))]
    public partial class BaseEntityOflong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseNamedEntityOflong", Namespace="")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ChemSW.Nbt.ChemWatchDocumentServices.DocumentLightWithMaterialAndVendor))]
    public partial class BaseNamedEntityOflong : ChemSW.Nbt.ChemWatchDocumentServices.BaseEntityOflong {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ChemWatchDocumentServices.IDocumentService")]
    public interface IDocumentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/CopyDocuments", ReplyAction="urn:IDocumentService/CopyDocumentsResponse")]
        bool CopyDocuments(int[] documentIds, int sourceFolderId, int destinationFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/MoveDocuments", ReplyAction="urn:IDocumentService/MoveDocumentsResponse")]
        bool MoveDocuments(int[] documentIds, int sourceFolderId, int destinationFolderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/GetDocumentsByMaterialId", ReplyAction="urn:IDocumentService/GetDocumentsByMaterialIdResponse")]
        ChemSW.Nbt.ChemWatchDocumentServices.ListResultOfDocument GetDocumentsByMaterialId(ChemSW.Nbt.ChemWatchDocumentServices.DocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/GetDocumentContent", ReplyAction="urn:IDocumentService/GetDocumentContentResponse")]
        System.IO.Stream GetDocumentContent(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/GetDocumentContentByExternalUrl", ReplyAction="urn:IDocumentService/GetDocumentContentByExternalUrlResponse")]
        System.IO.Stream GetDocumentContentByExternalUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/SaveMailRequest", ReplyAction="urn:IDocumentService/SaveMailRequestResponse")]
        string SaveMailRequest(long docId, string mailXmlString);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/GetDocuments", ReplyAction="urn:IDocumentService/GetDocumentsResponse")]
        ChemSW.Nbt.ChemWatchDocumentServices.DocumentLightWithMaterialAndVendor[] GetDocuments(int from, int to);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/CloneDocumentById", ReplyAction="urn:IDocumentService/CloneDocumentByIdResponse")]
        bool CloneDocumentById(byte[] document, string extension, string source, long docIdForClone);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:IDocumentService/CreateDocument", ReplyAction="urn:IDocumentService/CreateDocumentResponse")]
        bool CreateDocument(byte[] documentContent, string extension, ChemSW.Nbt.ChemWatchDocumentServices.DocumentLightWithMaterialAndVendor document);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceChannel : ChemSW.Nbt.ChemWatchDocumentServices.IDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.ClientBase<ChemSW.Nbt.ChemWatchDocumentServices.IDocumentService>, ChemSW.Nbt.ChemWatchDocumentServices.IDocumentService {
        
        public DocumentServiceClient() {
        }
        
        public DocumentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CopyDocuments(int[] documentIds, int sourceFolderId, int destinationFolderId) {
            return base.Channel.CopyDocuments(documentIds, sourceFolderId, destinationFolderId);
        }
        
        public bool MoveDocuments(int[] documentIds, int sourceFolderId, int destinationFolderId) {
            return base.Channel.MoveDocuments(documentIds, sourceFolderId, destinationFolderId);
        }
        
        public ChemSW.Nbt.ChemWatchDocumentServices.ListResultOfDocument GetDocumentsByMaterialId(ChemSW.Nbt.ChemWatchDocumentServices.DocumentRequest request) {
            return base.Channel.GetDocumentsByMaterialId(request);
        }
        
        public System.IO.Stream GetDocumentContent(string fileName) {
            return base.Channel.GetDocumentContent(fileName);
        }
        
        public System.IO.Stream GetDocumentContentByExternalUrl() {
            return base.Channel.GetDocumentContentByExternalUrl();
        }
        
        public string SaveMailRequest(long docId, string mailXmlString) {
            return base.Channel.SaveMailRequest(docId, mailXmlString);
        }
        
        public ChemSW.Nbt.ChemWatchDocumentServices.DocumentLightWithMaterialAndVendor[] GetDocuments(int from, int to) {
            return base.Channel.GetDocuments(from, to);
        }
        
        public bool CloneDocumentById(byte[] document, string extension, string source, long docIdForClone) {
            return base.Channel.CloneDocumentById(document, extension, source, docIdForClone);
        }
        
        public bool CreateDocument(byte[] documentContent, string extension, ChemSW.Nbt.ChemWatchDocumentServices.DocumentLightWithMaterialAndVendor document) {
            return base.Channel.CreateDocument(documentContent, extension, document);
        }
    }
}
